/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect, useRef, useCallback } from 'react';
import { MapContainer, TileLayer, Polyline, useMap, Marker, CircleMarker } from 'react-leaflet';
import { 
  Play, 
  Square, 
  Navigation, 
  TrendingUp, 
  Zap, 
  Map as MapIcon, 
  History, 
  Settings as SettingsIcon,
  Mountain,
  Timer,
  Activity,
  Sparkles,
  Globe,
  X,
  Users
} from 'lucide-react';
import { io, Socket } from 'socket.io-client';

type Language = 'en' | 'de' | 'es' | 'pl';

const translations = {
  en: {
    trackingActive: 'Tracking Active',
    readyToStart: 'Ready to Start',
    duration: 'Duration',
    distance: 'Distance',
    altitude: 'Altitude',
    speed: 'Speed',
    maxSpeed: 'Max Speed',
    start: 'Start',
    stop: 'Stop',
    gpsStatus: 'GPS Status',
    locked: 'Locked',
    searching: 'Searching...',
    requiredLocation: 'Location Required',
    locationDesc: 'To track your ski route, the app needs GPS access.',
    shareLocation: 'Share Location',
    gpsError: 'GPS Error',
    noPermission: 'No Permission',
    tryAgain: 'Try Again',
    settings: 'Settings',
    selectLanguage: 'Select Language',
    close: 'Close',
    download: 'Download',
    iconTitle: 'SkiTrack Pro Icon',
    iconDesc: 'Your new app icon has been generated by AI.',
    gpsSignalWeak: 'GPS signal is too weak. Go outside.',
    gpsTimeout: 'GPS signal timeout.',
    gpsPermissionDenied: 'Location permission denied. Check phone settings.',
    room: 'Room',
    createJoinRoom: 'Create or Join Room',
    roomName: 'Room Name',
    password: 'Password',
    userName: 'Your Name',
    join: 'Join',
    leave: 'Leave Room',
    invalidPassword: 'Invalid password',
    connectedToRoom: 'Connected to room',
    otherUsers: 'Other Users'
  },
  de: {
    trackingActive: 'Tracking Aktiv',
    readyToStart: 'Bereit zum Start',
    duration: 'Dauer',
    distance: 'Entfernung',
    altitude: 'Höhe',
    speed: 'Tempo',
    maxSpeed: 'Max. Tempo',
    start: 'Start',
    stop: 'Stopp',
    gpsStatus: 'GPS-Status',
    locked: 'Gesperrt',
    searching: 'Suche...',
    requiredLocation: 'Standort Erforderlich',
    locationDesc: 'Um Ihre Skiroute zu verfolgen, benötigt die App GPS-Zugriff.',
    shareLocation: 'Standort Freigeben',
    gpsError: 'GPS-Fehler',
    noPermission: 'Keine Berechtigung',
    tryAgain: 'Erneut Versuchen',
    settings: 'Einstellungen',
    selectLanguage: 'Sprache Wählen',
    close: 'Schließen',
    download: 'Herunterladen',
    iconTitle: 'SkiTrack Pro Icon',
    iconDesc: 'Ihr neues App-Icon wurde von KI generiert.',
    gpsSignalWeak: 'GPS-Signal zu schwach. Gehen Sie nach draußen.',
    gpsTimeout: 'GPS-Signal Zeitüberschreitung.',
    gpsPermissionDenied: 'Standortberechtigung verweigert. Einstellungen prüfen.',
    room: 'Raum',
    createJoinRoom: 'Raum erstellen oder beitreten',
    roomName: 'Raumname',
    password: 'Passwort',
    userName: 'Ihr Name',
    join: 'Beitreten',
    leave: 'Raum verlassen',
    invalidPassword: 'Ungültiges Passwort',
    connectedToRoom: 'Mit Raum verbunden',
    otherUsers: 'Andere Benutzer'
  },
  es: {
    trackingActive: 'Seguimiento Activo',
    readyToStart: 'Listo para Empezar',
    duration: 'Duración',
    distance: 'Distancia',
    altitude: 'Altitud',
    speed: 'Velocidad',
    maxSpeed: 'Vel. Máxima',
    start: 'Empezar',
    stop: 'Detener',
    gpsStatus: 'Estado GPS',
    locked: 'Bloqueado',
    searching: 'Buscando...',
    requiredLocation: 'Ubicación Requerida',
    locationDesc: 'Para rastrear tu ruta de esquí, la aplicación necesita acceso GPS.',
    shareLocation: 'Compartir Ubicación',
    gpsError: 'Error de GPS',
    noPermission: 'Sin Permiso',
    tryAgain: 'Reintentar',
    settings: 'Ajustes',
    selectLanguage: 'Seleccionar Idioma',
    close: 'Cerrar',
    download: 'Descargar',
    iconTitle: 'Icono SkiTrack Pro',
    iconDesc: 'Tu nuevo icono de aplicación ha sido generado por IA.',
    gpsSignalWeak: 'Señal GPS débil. Sal al exterior.',
    gpsTimeout: 'Tiempo de espera de GPS agotado.',
    gpsPermissionDenied: 'Permiso de ubicación denegado. Revisa los ajustes.',
    room: 'Sala',
    createJoinRoom: 'Crear o unirse a sala',
    roomName: 'Nombre de la sala',
    password: 'Contraseña',
    userName: 'Tu nombre',
    join: 'Unirse',
    leave: 'Salir de la sala',
    invalidPassword: 'Contraseña incorrecta',
    connectedToRoom: 'Conectado a la sala',
    otherUsers: 'Otros usuarios'
  },
  pl: {
    trackingActive: 'Śledzenie Aktywne',
    readyToStart: 'Gotowy do Startu',
    duration: 'Czas',
    distance: 'Dystans',
    altitude: 'Wysokość',
    speed: 'Prędkość',
    maxSpeed: 'Prędkość Maks.',
    start: 'Start',
    stop: 'Stop',
    gpsStatus: 'Status GPS',
    locked: 'Zablokowano',
    searching: 'Szukanie...',
    requiredLocation: 'Wymagana Lokalizacja',
    locationDesc: 'Aby śledzić Twoją trasę na nartach, aplikacja potrzebuje dostępu do GPS.',
    shareLocation: 'Udostępnij Lokalizację',
    gpsError: 'Błąd GPS',
    noPermission: 'Brak Uprawnień',
    tryAgain: 'Spróbuj Ponownie',
    settings: 'Ustawienia',
    selectLanguage: 'Wybierz Język',
    close: 'Zamknij',
    download: 'Pobierz',
    iconTitle: 'Ikona SkiTrack Pro',
    iconDesc: 'Twoja nowa ikona aplikacji została wygenerowana przez AI.',
    gpsSignalWeak: 'Sygnał GPS jest zbyt słaby. Wyjdź na zewnątrz.',
    gpsTimeout: 'Przekroczono czas oczekiwania na sygnał GPS.',
    gpsPermissionDenied: 'Brak uprawnień do lokalizacji. Sprawdź ustawienia telefonu.',
    room: 'Pokój',
    createJoinRoom: 'Stwórz lub dołącz do pokoju',
    roomName: 'Nazwa pokoju',
    password: 'Hasło',
    userName: 'Twoje imię',
    join: 'Dołącz',
    leave: 'Opuść pokój',
    invalidPassword: 'Błędne hasło',
    connectedToRoom: 'Połączono z pokojem',
    otherUsers: 'Inni użytkownicy'
  }
};
import { motion, AnimatePresence } from 'motion/react';
import L from 'leaflet';
import { GeoPoint, SessionStats } from './types';
import { generateAppIcon } from './services/iconService';

// Fix Leaflet marker icons
// @ts-ignore
delete L.Icon.Default.prototype._getIconUrl;
L.Icon.Default.mergeOptions({
  iconRetinaUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/images/marker-icon-2x.png',
  iconUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/images/marker-icon.png',
  shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/images/marker-shadow.png',
});

// Helper to calculate distance between two points (Haversine formula)
const calculateDistance = (p1: { lat: number, lng: number }, p2: { lat: number, lng: number }) => {
  const R = 6371e3; // metres
  const φ1 = p1.lat * Math.PI / 180;
  const φ2 = p2.lat * Math.PI / 180;
  const Δφ = (p2.lat - p1.lat) * Math.PI / 180;
  const Δλ = (p2.lng - p1.lng) * Math.PI / 180;

  const a = Math.sin(Δφ / 2) * Math.sin(Δφ / 2) +
    Math.cos(φ1) * Math.cos(φ2) *
    Math.sin(Δλ / 2) * Math.sin(Δλ / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

  return R * c;
};

function MapUpdater({ center, follow }: { center: [number, number], follow: boolean }) {
  const map = useMap();
  
  useEffect(() => {
    // Fix for partial map loading - run once when map is ready
    const timer = setTimeout(() => {
      map.invalidateSize();
    }, 500);
    return () => clearTimeout(timer);
  }, [map]);

  useEffect(() => {
    if (follow) {
      map.setView(center, map.getZoom(), { animate: true });
    }
  }, [center, map, follow]);
  return null;
}

export default function App() {
  const [isTracking, setIsTracking] = useState(false);
  const [route, setRoute] = useState<GeoPoint[]>([]);
  const [currentPos, setCurrentPos] = useState<[number, number] | null>(null);
  const [isLocating, setIsLocating] = useState(false);
  const [locationError, setLocationError] = useState<string | null>(null);
  const [permissionStatus, setPermissionStatus] = useState<PermissionState | 'unknown'>('unknown');
  const [hasStarted, setHasStarted] = useState(false);
  const [followUser, setFollowUser] = useState(true);
  const [stats, setStats] = useState<SessionStats>({
    distance: 0,
    maxSpeed: 0,
    avgSpeed: 0,
    totalTime: 0,
    elevationGain: 0,
    elevationLoss: 0
  });
  const [startTime, setStartTime] = useState<number | null>(null);
  const [elapsedTime, setElapsedTime] = useState(0);
  const [appIcon, setAppIcon] = useState<string | null>(null);
  const [isGeneratingIcon, setIsGeneratingIcon] = useState(false);
  const [language, setLanguage] = useState<Language>('pl');
  const [showSettings, setShowSettings] = useState(false);
  const [showRoomModal, setShowRoomModal] = useState(false);
  const [roomName, setRoomName] = useState('');
  const [roomPassword, setRoomPassword] = useState('');
  const [userName, setUserName] = useState('');
  const [joinedRoom, setJoinedRoom] = useState<string | null>(null);
  const [otherUsers, setOtherUsers] = useState<Map<string, { name: string, lat: number, lng: number }>>(new Map());
  
  const socketRef = useRef<Socket | null>(null);
  const t = translations[language];
  
  const watchId = useRef<number | null>(null);
  const timerInterval = useRef<NodeJS.Timeout | null>(null);
  const statsRef = useRef<SessionStats>(stats);
  const routeRef = useRef<GeoPoint[]>([]);
  const startTimeRef = useRef<number | null>(null);

  // Sync refs with state for tracking logic
  useEffect(() => {
    statsRef.current = stats;
  }, [stats]);

  useEffect(() => {
    routeRef.current = route;
  }, [route]);

  useEffect(() => {
    startTimeRef.current = startTime;
  }, [startTime]);

  // Start/Stop Tracking
  const toggleTracking = useCallback(() => {
    if (isTracking) {
      // Stop
      if (watchId.current !== null) {
        navigator.geolocation.clearWatch(watchId.current);
        watchId.current = null;
      }
      if (timerInterval.current) {
        clearInterval(timerInterval.current);
      }
      setIsTracking(false);
    } else {
      // Start
      setIsTracking(true);
      const now = Date.now();
      setStartTime(now);
      startTimeRef.current = now;
      setRoute([]);
      routeRef.current = [];
      setElapsedTime(0);
      const initialStats = {
        distance: 0,
        maxSpeed: 0,
        avgSpeed: 0,
        totalTime: 0,
        elevationGain: 0,
        elevationLoss: 0
      };
      setStats(initialStats);
      statsRef.current = initialStats;
      
      timerInterval.current = setInterval(() => {
        setElapsedTime(prev => prev + 1000);
      }, 1000);

      watchId.current = navigator.geolocation.watchPosition(
        (position) => {
          const { latitude, longitude, speed, altitude } = position.coords;
          const newPoint: GeoPoint = {
            lat: latitude,
            lng: longitude,
            timestamp: position.timestamp,
            speed: speed || 0,
            altitude: altitude || 0
          };

          setCurrentPos([latitude, longitude]);
          
          const lastPoint = routeRef.current[routeRef.current.length - 1];
          if (lastPoint) {
            const d = calculateDistance(lastPoint, newPoint);
            // Only add if moved more than 2 meters to avoid jitter
            if (d > 2) {
              const currentStats = statsRef.current;
              const newDistance = currentStats.distance + d;
              const newMaxSpeed = Math.max(currentStats.maxSpeed, speed || 0);
              
              let elevationGain = currentStats.elevationGain;
              let elevationLoss = currentStats.elevationLoss;
              
              if (altitude !== null && lastPoint.altitude !== null) {
                const diff = altitude - lastPoint.altitude;
                if (diff > 0.5) elevationGain += diff; // Filter small noise
                if (diff < -0.5) elevationLoss += Math.abs(diff);
              }
              
              const updatedStats = {
                ...currentStats,
                distance: newDistance,
                maxSpeed: newMaxSpeed,
                elevationGain,
                elevationLoss,
                avgSpeed: newDistance / ((Date.now() - (startTimeRef.current || Date.now())) / 1000)
              };

              setStats(updatedStats);
              statsRef.current = updatedStats;
              setRoute(prev => [...prev, newPoint]);
              routeRef.current = [...routeRef.current, newPoint];
            }
          } else {
            setRoute([newPoint]);
            routeRef.current = [newPoint];
          }
        },
        (error) => console.error("Geolocation error:", error),
        { 
          enableHighAccuracy: true,
          timeout: 10000,
          maximumAge: 0
        }
      );
    }
  }, [isTracking]);

  // Initial position
  const getInitialLocation = useCallback(async () => {
    if (!navigator.geolocation) {
      setLocationError("Twoje urządzenie nie obsługuje geolokalizacji.");
      return;
    }

    setIsLocating(true);
    setLocationError(null);
    setHasStarted(true);

    // Check permission status if API is available
    if ('permissions' in navigator) {
      try {
        const status = await navigator.permissions.query({ name: 'geolocation' });
        setPermissionStatus(status.state);
        status.onchange = () => setPermissionStatus(status.state);
      } catch (e) {
        console.warn("Permissions API not supported for geolocation");
      }
    }

    const options: PositionOptions = {
      enableHighAccuracy: true,
      timeout: 20000,
      maximumAge: 0
    };

    navigator.geolocation.getCurrentPosition(
      (pos) => {
        setCurrentPos([pos.coords.latitude, pos.coords.longitude]);
        setIsLocating(false);
        setPermissionStatus('granted');
      },
      (err) => {
        console.error("Initial location error:", err);
        let msg = t.gpsError;
        if (err.code === 1) {
          msg = t.gpsPermissionDenied;
          setPermissionStatus('denied');
        } else if (err.code === 2) {
          msg = t.gpsSignalWeak;
        } else if (err.code === 3) {
          msg = t.gpsTimeout;
        }
        setLocationError(msg);
        setIsLocating(false);
      },
      options
    );
  }, []);

  // No auto-start to avoid browser blocking
  useEffect(() => {
    // Just check permission status without requesting
    if ('permissions' in navigator) {
      navigator.permissions.query({ name: 'geolocation' })
        .then(status => setPermissionStatus(status.state))
        .catch(() => {});
    }
  }, []);

  // WebSocket setup
  useEffect(() => {
    socketRef.current = io();

    socketRef.current.on('user-location-update', ({ id, lat, lng }) => {
      setOtherUsers(prev => {
        const next = new Map(prev);
        const user = next.get(id) as { name: string, lat: number, lng: number } | undefined;
        if (user) {
          next.set(id, { name: user.name, lat, lng });
        }
        return next;
      });
    });

    socketRef.current.on('room-users', (users: any[]) => {
      const usersMap = new Map();
      users.forEach(u => {
        if (u.id !== socketRef.current?.id) {
          usersMap.set(u.id, { name: u.name, lat: u.lat, lng: u.lng });
        }
      });
      setOtherUsers(usersMap);
    });

    socketRef.current.on('user-left', (id: string) => {
      setOtherUsers(prev => {
        const next = new Map(prev);
        next.delete(id);
        return next;
      });
    });

    socketRef.current.on('joined-room', ({ roomName }) => {
      setJoinedRoom(roomName);
      setShowRoomModal(false);
    });

    socketRef.current.on('error', (msg: string) => {
      alert(msg === 'Invalid password' ? t.invalidPassword : msg);
    });

    return () => {
      socketRef.current?.disconnect();
    };
  }, [t.invalidPassword]);

  // Update location in room
  useEffect(() => {
    if (joinedRoom && currentPos && socketRef.current) {
      socketRef.current.emit('update-location', {
        roomName: joinedRoom,
        lat: currentPos[0],
        lng: currentPos[1]
      });
    }
  }, [currentPos, joinedRoom]);

  const joinRoom = () => {
    if (!roomName || !roomPassword || !userName) return;
    socketRef.current?.emit('join-room', { roomName, password: roomPassword, userName });
  };

  const leaveRoom = () => {
    socketRef.current?.emit('leave-room');
    setJoinedRoom(null);
    setOtherUsers(new Map());
  };

  const centerMap = () => {
    if (currentPos) {
      setFollowUser(true);
    }
  };

  const formatTime = (ms: number) => {
    const seconds = Math.floor((ms / 1000) % 60);
    const minutes = Math.floor((ms / (1000 * 60)) % 60);
    const hours = Math.floor(ms / (1000 * 60 * 60));
    return `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
  };

  const formatSpeed = (ms: number) => (ms * 3.6).toFixed(1); // m/s to km/h

  const handleGenerateIcon = async () => {
    setIsGeneratingIcon(true);
    try {
      const icon = await generateAppIcon();
      setAppIcon(icon);
    } catch (error) {
      console.error("Failed to generate icon:", error);
    } finally {
      setIsGeneratingIcon(false);
    }
  };

  return (
    <div className="flex flex-col h-screen bg-zinc-950 overflow-hidden">
      {/* Header */}
      <header className="flex items-center justify-between px-4 py-3 border-b border-zinc-800 bg-zinc-900/80 backdrop-blur-md z-50">
        <div className="flex items-center gap-2">
          <div className="p-1.5 bg-emerald-500/10 rounded-lg">
            <Mountain className="w-5 h-5 text-emerald-500" />
          </div>
          <div>
            <h1 className="text-base font-bold tracking-tight leading-none">SkiTrack Pro</h1>
            <p className="text-[10px] text-zinc-500 font-mono uppercase tracking-wider mt-0.5">
              {isTracking ? t.trackingActive : t.readyToStart}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-4">
          <div className="flex flex-col items-end">
            <span className="text-[10px] text-zinc-500 font-mono uppercase leading-none mb-1">{t.duration}</span>
            <span className="text-lg font-mono font-bold text-emerald-400 leading-none">{formatTime(elapsedTime)}</span>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 relative">
        {/* Loading / Error / Start States */}
        <AnimatePresence>
          {(!hasStarted || isLocating || locationError) && (
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 z-[60] bg-zinc-950 flex flex-col items-center justify-center p-8 text-center"
            >
              {!hasStarted ? (
                <>
                  <div className="p-6 bg-emerald-500/10 rounded-full mb-6">
                    <Navigation className="w-12 h-12 text-emerald-500" />
                  </div>
                  <h2 className="text-2xl font-bold text-zinc-100 mb-3">{t.requiredLocation}</h2>
                  <p className="text-zinc-400 mb-8 max-w-xs">
                    {t.locationDesc}
                  </p>
                  <button 
                    onClick={getInitialLocation}
                    className="w-full max-w-xs py-4 bg-emerald-500 hover:bg-emerald-600 text-white rounded-2xl font-bold text-lg transition-all shadow-xl shadow-emerald-500/20"
                  >
                    {t.shareLocation}
                  </button>
                </>
              ) : isLocating ? (
                <>
                  <div className="w-12 h-12 border-4 border-emerald-500/20 border-t-emerald-500 rounded-full animate-spin mb-4" />
                  <p className="text-zinc-400 font-medium tracking-wide">{t.searching}</p>
                  <p className="text-zinc-500 text-sm mt-2">{t.gpsSignalWeak}</p>
                </>
              ) : (
                <>
                  <div className="p-4 bg-red-500/10 rounded-full mb-4">
                    <Activity className="w-8 h-8 text-red-500" />
                  </div>
                  <h2 className="text-xl font-bold text-zinc-100 mb-2">
                    {permissionStatus === 'denied' ? t.noPermission : t.gpsError}
                  </h2>
                  <p className="text-zinc-400 mb-6 max-w-xs">{locationError}</p>
                  <button 
                    onClick={getInitialLocation}
                    className="px-8 py-4 bg-emerald-500 hover:bg-emerald-600 text-white rounded-2xl font-bold transition-all shadow-xl shadow-emerald-500/20"
                  >
                    {t.tryAgain}
                  </button>
                  <p className="text-zinc-500 text-xs mt-6 max-w-[240px]">
                    Jeśli używasz aplikacji APK, upewnij się, że przy jej tworzeniu zaznaczono uprawnienia GPS (ACCESS_FINE_LOCATION).
                  </p>
                </>
              )}
            </motion.div>
          )}
        </AnimatePresence>

        {/* Map Container */}
        <div className="absolute inset-0 z-0">
          {currentPos && (
            <MapContainer 
              center={currentPos} 
              zoom={15} 
              zoomControl={false}
              className="w-full h-full"
              preferCanvas={true}
            >
              <TileLayer
                url="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
                attribution='Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community'
              />
              <TileLayer
                url={`https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}`}
                attribution='Labels &copy; Esri &mdash; Source: Esri, DeLorme, NAVTEQ, TomTom, and others'
                zIndex={1000}
              />
              <TileLayer
                url="https://tile.waymarkedtrails.org/slopes/{z}/{x}/{y}.png"
                attribution='&copy; <a href="https://slopes.waymarkedtrails.org">Waymarked Trails</a>'
                zIndex={900}
                opacity={0.8}
              />
              <MapUpdater center={currentPos} follow={followUser} />
              
              {route.length > 1 && (
                <Polyline 
                  positions={route.map(p => [p.lat, p.lng])} 
                  color="#ef4444" 
                  weight={6}
                  opacity={1}
                />
              )}
              
              {currentPos && (
                <CircleMarker 
                  center={currentPos} 
                  radius={8}
                  pathOptions={{ fillColor: '#ef4444', fillOpacity: 1, color: 'white', weight: 3 }}
                />
              )}

              {Array.from(otherUsers.entries()).map(([id, user]) => (
                user.lat !== 0 && (
                  <Marker 
                    key={id} 
                    position={[user.lat, user.lng]}
                    icon={L.divIcon({
                      className: 'custom-div-icon',
                      html: `<div class="flex flex-col items-center">
                        <div class="bg-emerald-500 text-white text-[10px] font-bold px-1.5 py-0.5 rounded shadow-lg whitespace-nowrap mb-1 border border-white/20">${user.name}</div>
                        <div class="w-3 h-3 bg-emerald-500 rounded-full border-2 border-white shadow-lg"></div>
                      </div>`,
                      iconSize: [0, 0],
                      iconAnchor: [0, 0]
                    })}
                  />
                )
              ))}
            </MapContainer>
          )}
        </div>

        {/* Stats Overlay - Top */}
        <div className="absolute top-3 left-3 right-3 grid grid-cols-2 gap-2 z-10">
          <StatCard 
            label={t.distance} 
            value={(stats.distance / 1000).toFixed(2)} 
            unit="km" 
            icon={<Navigation className="w-3.5 h-3.5" />} 
          />
          <StatCard 
            label={t.altitude} 
            value={(route[route.length - 1]?.altitude || 0).toFixed(0)} 
            unit="m" 
            icon={<Mountain className="w-3.5 h-3.5" />} 
          />
          <StatCard 
            label={t.speed} 
            value={formatSpeed(route[route.length - 1]?.speed || 0)} 
            unit="km/h" 
            icon={<Zap className="w-3.5 h-3.5" />} 
          />
          <StatCard 
            label={t.maxSpeed} 
            value={formatSpeed(stats.maxSpeed)} 
            unit="km/h" 
            icon={<TrendingUp className="w-3.5 h-3.5" />} 
          />
        </div>

        {/* Controls - Bottom */}
        <div className="absolute bottom-8 left-0 right-0 px-6 flex justify-center items-center gap-4 z-10">
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={toggleTracking}
            className={`flex-1 max-w-[240px] flex items-center justify-center gap-3 py-4 rounded-2xl font-bold text-lg shadow-2xl transition-colors ${
              isTracking 
                ? 'bg-red-500 text-white' 
                : 'bg-emerald-500 text-white'
            }`}
          >
            {isTracking ? (
              <>
                <Square className="w-5 h-5 fill-current" />
                {t.stop}
              </>
            ) : (
              <>
                <Play className="w-5 h-5 fill-current" />
                {t.start}
              </>
            )}
          </motion.button>
        </div>

        {/* Side Controls */}
        <div className="absolute right-3 bottom-28 flex flex-col gap-2 z-10">
          <IconButton 
            onClick={() => setShowRoomModal(true)}
            active={!!joinedRoom}
            icon={<Users className={`w-5 h-5 ${joinedRoom ? 'text-emerald-500' : 'text-zinc-400'}`} />} 
          />
          <IconButton 
            onClick={() => setShowSettings(true)}
            icon={<SettingsIcon className="w-5 h-5" />} 
          />
          <IconButton 
            active={followUser}
            onClick={() => setFollowUser(!followUser)}
            icon={<Navigation className={`w-5 h-5 ${followUser ? 'text-emerald-500' : 'text-zinc-400'}`} />} 
          />
          <IconButton 
            onClick={centerMap}
            icon={<MapIcon className="w-5 h-5" />} 
          />
          <IconButton 
            onClick={handleGenerateIcon}
            active={!!appIcon}
            icon={isGeneratingIcon ? <div className="w-5 h-5 border-2 border-emerald-500/20 border-t-emerald-500 rounded-full animate-spin" /> : <Sparkles className="w-5 h-5" />} 
          />
          <IconButton icon={<History className="w-5 h-5" />} />
        </div>

        {/* App Icon Preview Modal */}
        <AnimatePresence>
          {appIcon && (
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 z-[70] bg-zinc-950/90 backdrop-blur-md flex flex-col items-center justify-center p-8"
            >
              <div className="relative group">
                <img 
                  src={appIcon} 
                  alt="App Icon" 
                  className="w-64 h-64 rounded-[4rem] shadow-2xl border-4 border-zinc-800"
                />
                <div className="absolute -inset-4 bg-emerald-500/20 blur-3xl -z-10 group-hover:opacity-100 transition-opacity" />
              </div>
              <h2 className="text-2xl font-bold text-zinc-100 mt-8 mb-2">{t.iconTitle}</h2>
              <p className="text-zinc-400 text-center mb-8 max-w-xs">{t.iconDesc}</p>
              <div className="flex gap-4">
                <button 
                  onClick={() => setAppIcon(null)}
                  className="px-8 py-3 bg-zinc-800 hover:bg-zinc-700 text-zinc-100 rounded-xl font-bold transition-colors"
                >
                  {t.close}
                </button>
                <a 
                  href={appIcon} 
                  download="skitrack-icon.png"
                  className="px-8 py-3 bg-emerald-500 hover:bg-emerald-600 text-white rounded-xl font-bold transition-colors"
                >
                  {t.download}
                </a>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Room Modal */}
        <AnimatePresence>
          {showRoomModal && (
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 z-[80] bg-zinc-950/95 backdrop-blur-xl flex flex-col items-center justify-center p-6"
            >
              <div className="w-full max-w-sm bg-zinc-900 border border-zinc-800 rounded-3xl p-6 shadow-2xl">
                <div className="flex justify-between items-center mb-6">
                  <div className="flex items-center gap-3">
                    <div className="p-2 bg-emerald-500/10 rounded-lg">
                      <Users className="w-5 h-5 text-emerald-500" />
                    </div>
                    <h2 className="text-xl font-bold text-zinc-100">{t.room}</h2>
                  </div>
                  <button 
                    onClick={() => setShowRoomModal(false)}
                    className="p-2 hover:bg-zinc-800 rounded-full transition-colors"
                  >
                    <X className="w-6 h-6 text-zinc-500" />
                  </button>
                </div>

                {joinedRoom ? (
                  <div className="space-y-6">
                    <div className="p-4 bg-emerald-500/5 border border-emerald-500/20 rounded-2xl">
                      <p className="text-zinc-400 text-sm mb-1">{t.connectedToRoom}</p>
                      <p className="text-xl font-bold text-emerald-500">{joinedRoom}</p>
                    </div>
                    
                    <div>
                      <h3 className="text-xs font-bold text-zinc-500 uppercase tracking-widest mb-3">{t.otherUsers} ({otherUsers.size})</h3>
                      <div className="space-y-2 max-h-40 overflow-y-auto pr-2 custom-scrollbar">
                        {Array.from(otherUsers.entries()).map(([id, user]) => {
                          const userData = user as { name: string, lat: number, lng: number };
                          return (
                            <div key={id} className="flex items-center gap-3 p-3 bg-zinc-800/50 rounded-xl border border-zinc-800">
                              <div className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse" />
                              <span className="text-zinc-200 font-medium">{userData.name}</span>
                            </div>
                          );
                        })}
                        {otherUsers.size === 0 && (
                          <p className="text-zinc-600 text-sm italic py-2">Brak innych osób w pokoju</p>
                        )}
                      </div>
                    </div>

                    <button 
                      onClick={leaveRoom}
                      className="w-full py-4 bg-red-500/10 hover:bg-red-500/20 text-red-500 border border-red-500/20 rounded-2xl font-bold transition-colors"
                    >
                      {t.leave}
                    </button>
                  </div>
                ) : (
                  <div className="space-y-4">
                    <p className="text-zinc-400 text-sm mb-4">{t.createJoinRoom}</p>
                    
                    <div>
                      <label className="block text-[10px] font-bold text-zinc-500 uppercase tracking-wider mb-1.5 ml-1">{t.userName}</label>
                      <input 
                        type="text" 
                        value={userName}
                        onChange={(e) => setUserName(e.target.value)}
                        placeholder="np. Marek"
                        className="w-full bg-zinc-800 border border-zinc-700 rounded-xl py-3 px-4 text-zinc-100 focus:outline-none focus:border-emerald-500 transition-colors"
                      />
                    </div>

                    <div>
                      <label className="block text-[10px] font-bold text-zinc-500 uppercase tracking-wider mb-1.5 ml-1">{t.roomName}</label>
                      <input 
                        type="text" 
                        value={roomName}
                        onChange={(e) => setRoomName(e.target.value)}
                        placeholder="Nazwa grupy"
                        className="w-full bg-zinc-800 border border-zinc-700 rounded-xl py-3 px-4 text-zinc-100 focus:outline-none focus:border-emerald-500 transition-colors"
                      />
                    </div>

                    <div>
                      <label className="block text-[10px] font-bold text-zinc-500 uppercase tracking-wider mb-1.5 ml-1">{t.password}</label>
                      <input 
                        type="password" 
                        value={roomPassword}
                        onChange={(e) => setRoomPassword(e.target.value)}
                        placeholder="••••••"
                        className="w-full bg-zinc-800 border border-zinc-700 rounded-xl py-3 px-4 text-zinc-100 focus:outline-none focus:border-emerald-500 transition-colors"
                      />
                    </div>

                    <button 
                      onClick={joinRoom}
                      disabled={!roomName || !roomPassword || !userName}
                      className="w-full mt-4 py-4 bg-emerald-500 hover:bg-emerald-600 disabled:opacity-50 disabled:hover:bg-emerald-500 text-white rounded-2xl font-bold text-lg transition-all shadow-xl shadow-emerald-500/20"
                    >
                      {t.join}
                    </button>
                  </div>
                )}

                <button 
                  onClick={() => setShowRoomModal(false)}
                  className="w-full mt-4 py-3 text-zinc-500 hover:text-zinc-300 font-medium transition-colors"
                >
                  {t.close}
                </button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Settings Modal */}
        <AnimatePresence>
          {showSettings && (
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 z-[80] bg-zinc-950/95 backdrop-blur-xl flex flex-col items-center justify-center p-6"
            >
              <div className="w-full max-w-sm bg-zinc-900 border border-zinc-800 rounded-3xl p-6 shadow-2xl">
                <div className="flex justify-between items-center mb-8">
                  <div className="flex items-center gap-3">
                    <div className="p-2 bg-emerald-500/10 rounded-lg">
                      <SettingsIcon className="w-5 h-5 text-emerald-500" />
                    </div>
                    <h2 className="text-xl font-bold text-zinc-100">{t.settings}</h2>
                  </div>
                  <button 
                    onClick={() => setShowSettings(false)}
                    className="p-2 hover:bg-zinc-800 rounded-full transition-colors"
                  >
                    <X className="w-6 h-6 text-zinc-500" />
                  </button>
                </div>

                <div className="space-y-6">
                  <div>
                    <div className="flex items-center gap-2 text-zinc-400 mb-4">
                      <Globe className="w-4 h-4" />
                      <span className="text-sm font-bold uppercase tracking-wider">{t.selectLanguage}</span>
                    </div>
                    <div className="grid grid-cols-2 gap-3">
                      {(['en', 'de', 'es', 'pl'] as Language[]).map((lang) => (
                        <button
                          key={lang}
                          onClick={() => setLanguage(lang)}
                          className={`py-3 px-4 rounded-xl font-bold transition-all border ${
                            language === lang 
                              ? 'bg-emerald-500 border-emerald-400 text-white shadow-lg shadow-emerald-500/20' 
                              : 'bg-zinc-800 border-zinc-700 text-zinc-400 hover:border-zinc-500'
                          }`}
                        >
                          {lang === 'en' ? 'English' : lang === 'de' ? 'Deutsch' : lang === 'es' ? 'Español' : 'Polski'}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>

                <button 
                  onClick={() => setShowSettings(false)}
                  className="w-full mt-10 py-4 bg-zinc-800 hover:bg-zinc-700 text-zinc-100 rounded-2xl font-bold transition-colors"
                >
                  {t.close}
                </button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </main>

      {/* Footer / Status Bar */}
      <footer className="px-6 py-2 border-t border-zinc-800 bg-zinc-900 flex justify-between items-center text-[10px] text-zinc-500 font-mono uppercase tracking-widest">
        <div className="flex items-center gap-4">
          <span className="flex items-center gap-1">
            <div className={`w-1.5 h-1.5 rounded-full ${isTracking ? 'bg-emerald-500 animate-pulse' : 'bg-zinc-700'}`} />
            {t.gpsStatus}: {currentPos ? t.locked : t.searching}
          </span>
          <span>Lat: {currentPos?.[0].toFixed(4) || '---'}</span>
          <span>Lng: {currentPos?.[1].toFixed(4) || '---'}</span>
        </div>
        <div>v1.0.4-stable</div>
      </footer>
    </div>
  );
}

function StatCard({ label, value, unit, icon }: { label: string, value: string, unit: string, icon: React.ReactNode }) {
  return (
    <motion.div 
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      className="bg-zinc-900/90 backdrop-blur-xl border border-zinc-800 p-3 rounded-xl shadow-lg"
    >
      <div className="flex items-center gap-1.5 text-zinc-500 mb-0.5">
        {icon}
        <span className="text-[9px] font-bold uppercase tracking-wider truncate">{label}</span>
      </div>
      <div className="flex items-baseline gap-1">
        <span className="text-xl font-mono font-bold text-zinc-100">{value}</span>
        <span className="text-[10px] text-zinc-500 font-medium">{unit}</span>
      </div>
    </motion.div>
  );
}

function IconButton({ icon, onClick, active }: { icon: React.ReactNode, onClick?: () => void, active?: boolean }) {
  return (
    <button 
      onClick={onClick}
      className={`p-3 backdrop-blur-xl border rounded-xl transition-all shadow-lg ${
        active 
          ? 'bg-emerald-500/20 border-emerald-500/50 text-emerald-500' 
          : 'bg-zinc-900/90 border-zinc-800 text-zinc-400 hover:text-emerald-500'
      }`}
    >
      {icon}
    </button>
  );
}
