/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect, useRef, useCallback } from 'react';
import { MapContainer, TileLayer, Polyline, useMap, Marker, CircleMarker } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import { 
  Play, 
  Square, 
  Navigation, 
  TrendingUp, 
  ArrowDownRight,
  ArrowUpRight,
  Zap, 
  Settings as SettingsIcon,
  Mountain,
  Timer,
  Activity,
  Globe,
  X,
  Users,
  Mic,
  MicOff,
  Search,
  MapPin,
  ExternalLink
} from 'lucide-react';
import { io, Socket } from 'socket.io-client';
import { GoogleGenAI } from "@google/genai";

declare global {
  interface Window {
    aistudio?: {
      hasSelectedApiKey: () => Promise<boolean>;
      openSelectKey: () => Promise<void>;
    };
  }
}

type Language = 'en' | 'de' | 'es' | 'pl';

const translations = {
  en: {
    trackingActive: 'Tracking Active',
    readyToStart: 'Ready to Start',
    duration: 'Duration',
    distance: 'Distance',
    altitude: 'Altitude',
    speed: 'Speed',
    maxSpeed: 'Max Speed',
    avgSpeed: 'Avg. Speed',
    start: 'Start',
    stop: 'Stop',
    gpsStatus: 'GPS Status',
    locked: 'Locked',
    searching: 'Searching...',
    requiredLocation: 'Location Required',
    locationDesc: 'To track your ski route, the app needs GPS access.',
    shareLocation: 'Share Location',
    gpsError: 'GPS Error',
    noPermission: 'No Permission',
    tryAgain: 'Try Again',
    settings: 'Settings',
    selectLanguage: 'Select Language',
    close: 'Close',
    download: 'Download',
    iconTitle: 'SkiTrack Icon',
    iconDesc: 'Your new app icon has been generated by AI.',
    gpsSignalWeak: 'GPS signal is too weak. Go outside.',
    gpsTimeout: 'GPS signal timeout.',
    gpsPermissionDenied: 'Location permission denied. Check phone settings.',
    room: 'Room',
    createJoinRoom: 'Create or Join Room',
    roomName: 'Room Name',
    password: 'Password',
    userName: 'Your Name',
    join: 'Join',
    leave: 'Leave Room',
    invalidPassword: 'Invalid password',
    connectedToRoom: 'Connected to room',
    otherUsers: 'Other Users',
    joiningRoom: 'Joining room...',
    roomJoinedSuccess: 'Successfully joined the room!',
    roomCreatedSuccess: 'Successfully created the room!',
    joinRoom: 'Join Room',
    createRoom: 'Create Room',
    roomAlreadyExists: 'Room already exists',
    roomDoesNotExist: 'Room does not exist',
    internalError: 'Internal server error',
    voiceChat: 'Voice Chat',
    micOn: 'Microphone On',
    micOff: 'Microphone Off',
    slope: 'Slope',
    maxAltitude: 'Max Altitude',
    maxSlope: 'Max Slope',
    minSlope: 'Min Slope',
    altitudeCalibration: 'Altitude Calibration',
    altitudeOffset: 'Altitude Offset',
    calibrationDesc: 'Adjust altitude if GPS shows incorrect data (e.g. above sea level).',
    autoCalibrate: 'Auto-Calibrate',
    calibrating: 'Calibrating...',
    calibrationSuccess: 'Altitude calibrated!',
    calibrationError: 'Calibration error',
    inAppBrowserWarning: 'In-app browser detected',
    inAppBrowserDesc: 'In-app browsers (Facebook, Messenger, Instagram, WhatsApp) often block GPS. For best experience, open this page in Chrome, Safari, Opera, or Edge.',
    openInBrowser: 'Open in Browser',
    falls8g: 'Falls 8g',
    falls5g: 'Falls 5g',
    startTutorial: 'Start Tutorial',
    tutorialSteps: [
      { title: 'Welcome', content: 'Welcome to the Ski Tracker! Let us show you around.' },
      { title: 'Tracking', content: 'Click the Play button to start tracking your session.' },
      { title: 'Stats', content: 'Swipe through the stats cards to see your speed, altitude, and more.' },
      { title: 'Map', content: 'See your real-time position and route on the map.' },
      { title: 'Rooms', content: 'Join or create a room to see your friends on the map and talk to them.' },
      { title: 'Search', content: 'Find ski resorts nearby or search for specific ones.' },
      { title: 'Settings', content: 'Change language and other options here.' },
      { title: 'Follow', content: 'Enable this to keep the map centered on your position.' }
    ],
    next: 'Next',
    finish: 'Finish',
    skip: 'Skip',
    searchResorts: 'Search Resorts',
    searchPlaceholder: 'Search for a resort...',
    nearbyResorts: 'Nearby Ski Resorts',
    noResortsFound: 'No resorts found nearby.',
    searchingResorts: 'Searching for resorts...',
    locationRequired: 'Location required for nearby search.'
  },
  de: {
    trackingActive: 'Tracking Aktiv',
    readyToStart: 'Bereit zum Start',
    duration: 'Dauer',
    distance: 'Entfernung',
    altitude: 'Höhe',
    speed: 'Tempo',
    maxSpeed: 'Max. Tempo',
    avgSpeed: 'Durchschn. Tempo',
    start: 'Start',
    stop: 'Stopp',
    gpsStatus: 'GPS-Status',
    locked: 'Gesperrt',
    searching: 'Suche...',
    requiredLocation: 'Standort Erforderlich',
    locationDesc: 'Um Ihre Skiroute zu verfolgen, benötigt die App GPS-Zugriff.',
    shareLocation: 'Standort Freigeben',
    gpsError: 'GPS-Fehler',
    noPermission: 'Keine Berechtigung',
    tryAgain: 'Erneut Versuchen',
    settings: 'Einstellungen',
    selectLanguage: 'Sprache Wählen',
    close: 'Schließen',
    download: 'Herunterladen',
    iconTitle: 'SkiTrack Pro Icon',
    iconDesc: 'Ihr neues App-Icon wurde von KI generiert.',
    gpsSignalWeak: 'GPS-Signal zu schwach. Gehen Sie nach draußen.',
    gpsTimeout: 'GPS-Signal Zeitüberschreitung.',
    gpsPermissionDenied: 'Standortberechtigung verweigert. Einstellungen prüfen.',
    room: 'Raum',
    createJoinRoom: 'Raum erstellen oder beitreten',
    roomName: 'Raumname',
    password: 'Passwort',
    userName: 'Ihr Name',
    join: 'Beitreten',
    leave: 'Raum verlassen',
    invalidPassword: 'Ungültiges Passwort',
    connectedToRoom: 'Mit Raum verbunden',
    otherUsers: 'Andere Benutzer',
    joiningRoom: 'Raum beitreten...',
    roomJoinedSuccess: 'Erfolgreich dem Raum beigetreten!',
    roomCreatedSuccess: 'Raum erfolgreich erstellt!',
    joinRoom: 'Raum beitreten',
    createRoom: 'Raum erstellen',
    roomAlreadyExists: 'Raum existiert bereits',
    roomDoesNotExist: 'Raum existiert nicht',
    internalError: 'Interner Serverfehler',
    voiceChat: 'Sprachchat',
    micOn: 'Mikrofon An',
    micOff: 'Mikrofon Aus',
    slope: 'Gefälle',
    maxAltitude: 'Max. Höhe',
    maxSlope: 'Max. Gefälle',
    minSlope: 'Min. Gefälle',
    falls8g: 'Stürze 8g',
    falls5g: 'Stürze 5g',
    startTutorial: 'Tutorial starten',
    tutorialSteps: [
      { title: 'Willkommen', content: 'Willkommen beim Ski Tracker! Lassen Sie sich von uns herumführen.' },
      { title: 'Tracking', content: 'Klicken Sie auf die Play-Schaltfläche, um Ihre Sitzung zu starten.' },
      { title: 'Statistiken', content: 'Wischen Sie durch die Statistik-Karten, um Geschwindigkeit, Höhe i.v.m. zu sehen.' },
      { title: 'Karte', content: 'Sehen Sie Ihre Echtzeit-Position und Route auf der Karte.' },
      { title: 'Räume', content: 'Treten Sie einem Raum bei oder erstellen Sie einen, um Ihre Freunde auf der Karte zu sehen und mit ihnen zu sprechen.' },
      { title: 'Suche', content: 'Finden Sie Skigebiete in der Nähe oder suchen Sie nach bestimmten Gebieten.' },
      { title: 'Einstellungen', content: 'Ändern Sie hier die Sprache und andere Optionen.' },
      { title: 'Folgen', content: 'Aktivieren Sie dies, damit die Karte auf Ihrer Position zentriert bleibt.' }
    ],
    next: 'Weiter',
    finish: 'Beenden',
    skip: 'Überspringen',
    searchResorts: 'Skigebiete suchen',
    searchPlaceholder: 'Nach einem Skigebiet suchen...',
    nearbyResorts: 'Skigebiete in der Nähe',
    noResortsFound: 'Keine Skigebiete in der Nähe gefunden.',
    searchingResorts: 'Suche nach Skigebieten...',
    locationRequired: 'Standort für die Suche in der Nähe erforderlich.'
  },
  es: {
    trackingActive: 'Seguimiento Activo',
    readyToStart: 'Listo para Empezar',
    duration: 'Duración',
    distance: 'Distancia',
    altitude: 'Altitud',
    speed: 'Velocidad',
    maxSpeed: 'Vel. Máxima',
    avgSpeed: 'Vel. Media',
    start: 'Empezar',
    stop: 'Detener',
    gpsStatus: 'Estado GPS',
    locked: 'Bloqueado',
    searching: 'Buscando...',
    requiredLocation: 'Ubicación Requerida',
    locationDesc: 'Para rastrear tu ruta de esquí, la aplicación necesita acceso GPS.',
    shareLocation: 'Compartir Ubicación',
    gpsError: 'Error de GPS',
    noPermission: 'Sin Permiso',
    tryAgain: 'Reintentar',
    settings: 'Ajustes',
    selectLanguage: 'Seleccionar Idioma',
    close: 'Cerrar',
    download: 'Descargar',
    iconTitle: 'Icono SkiTrack',
    iconDesc: 'Tu nuevo icono de aplicación ha sido generado por IA.',
    gpsSignalWeak: 'Señal GPS débil. Sal al exterior.',
    gpsTimeout: 'Tiempo de espera de GPS agotado.',
    gpsPermissionDenied: 'Permiso de ubicación denegado. Revisa los ajustes.',
    room: 'Sala',
    createJoinRoom: 'Crear o unirse a sala',
    roomName: 'Nombre de la sala',
    password: 'Contraseña',
    userName: 'Tu nombre',
    join: 'Unirse',
    leave: 'Salir de la sala',
    invalidPassword: 'Contraseña incorrecta',
    connectedToRoom: 'Conectado a la sala',
    otherUsers: 'Otros usuarios',
    joiningRoom: 'Uniéndose a la sala...',
    roomJoinedSuccess: '¡Te has unido a la sala con éxito!',
    roomCreatedSuccess: '¡Sala creada con éxito!',
    joinRoom: 'Unirse a sala',
    createRoom: 'Crear sala',
    roomAlreadyExists: 'La sala ya existe',
    roomDoesNotExist: 'La sala no existe',
    internalError: 'Error interno del servidor',
    voiceChat: 'Chat de voz',
    micOn: 'Micrófono encendido',
    micOff: 'Micrófono apagado',
    slope: 'Pendiente',
    maxAltitude: 'Alt. Máxima',
    maxSlope: 'Pendiente Máx.',
    minSlope: 'Pendiente Mín.',
    falls8g: 'Caídas 8g',
    falls5g: 'Caídas 5g',
    startTutorial: 'Iniciar Tutorial',
    tutorialSteps: [
      { title: 'Bienvenido', content: '¡Bienvenido al Ski Tracker! Permítenos mostrarte los alrededores.' },
      { title: 'Seguimiento', content: 'Haz clic en el botón Play para comenzar a rastrear tu sesión.' },
      { title: 'Estadísticas', content: 'Desliza las tarjetas de estadísticas para ver tu velocidad, altitud y más.' },
      { title: 'Mapa', content: 'Mira tu posición en tiempo real y tu ruta en el mapa.' },
      { title: 'Salas', content: 'Únete o crea una sala para ver a tus amigos en el mapa y hablar con ellos.' },
      { title: 'Buscar', content: 'Encuentra estaciones de esquí cercanas o busca estaciones específicas.' },
      { title: 'Ajustes', content: 'Cambia el idioma y otras opciones aquí.' },
      { title: 'Seguir', content: 'Activa esto para mantener el mapa centrado en tu posición.' }
    ],
    next: 'Siguiente',
    finish: 'Finalizar',
    skip: 'Omitir',
    searchResorts: 'Buscar Estaciones',
    searchPlaceholder: 'Buscar una estación...',
    nearbyResorts: 'Estaciones de Esquí Cercanas',
    noResortsFound: 'No se encontraron estaciones cercanas.',
    searchingResorts: 'Buscando estaciones...',
    locationRequired: 'Se requiere ubicación para búsqueda cercana.'
  },
  pl: {
    trackingActive: 'Śledzenie Aktywne',
    readyToStart: 'Gotowy do Startu',
    duration: 'Czas',
    distance: 'Dystans',
    altitude: 'Wysokość',
    speed: 'Prędkość',
    maxSpeed: 'Prędkość Maks.',
    avgSpeed: 'Prędkość Śr.',
    start: 'Start',
    stop: 'Stop',
    gpsStatus: 'Status GPS',
    locked: 'Zablokowano',
    searching: 'Szukanie...',
    requiredLocation: 'Wymagana Lokalizacja',
    locationDesc: 'Aby śledzić Twoją trasę na nartach, aplikacja potrzebuje dostępu do GPS.',
    shareLocation: 'Udostępnij Lokalizację',
    gpsError: 'Błąd GPS',
    noPermission: 'Brak Uprawnień',
    tryAgain: 'Spróbuj Ponownie',
    settings: 'Ustawienia',
    selectLanguage: 'Wybierz Język',
    close: 'Zamknij',
    download: 'Pobierz',
    iconTitle: 'Ikona SkiTrack',
    iconDesc: 'Twoja nowa ikona aplikacji została wygenerowana przez AI.',
    gpsSignalWeak: 'Sygnał GPS jest zbyt słaby. Wyjdź na zewnątrz.',
    gpsTimeout: 'Przekroczono czas oczekiwania na sygnał GPS.',
    gpsPermissionDenied: 'Brak uprawnień do lokalizacji. Sprawdź ustawienia telefonu.',
    room: 'Pokój',
    createJoinRoom: 'Stwórz lub dołącz do pokoju',
    roomName: 'Nazwa pokoju',
    password: 'Hasło',
    userName: 'Twoje imię',
    join: 'Dołącz',
    leave: 'Opuść pokój',
    invalidPassword: 'Błędne hasło',
    connectedToRoom: 'Połączono z pokojem',
    otherUsers: 'Inni użytkownicy',
    joiningRoom: 'Dołączanie do pokoju...',
    roomJoinedSuccess: 'Pomyślnie dołączono do pokoju!',
    roomCreatedSuccess: 'Pomyślnie stworzono pokój!',
    joinRoom: 'Dołącz do pokoju',
    createRoom: 'Stwórz pokój',
    roomAlreadyExists: 'Pokój o tej nazwie już istnieje',
    roomDoesNotExist: 'Pokój o tej nazwie nie istnieje',
    internalError: 'Błąd serwera',
    voiceChat: 'Czat głosowy',
    micOn: 'Mikrofon włączony',
    micOff: 'Mikrofon wyłączony',
    slope: 'Spadek',
    maxAltitude: 'Wysokość Maks.',
    maxSlope: 'Spadek Maks.',
    minSlope: 'Spadek Min.',
    altitudeCalibration: 'Kalibracja Wysokości',
    altitudeOffset: 'Offset Wysokości',
    calibrationDesc: 'Dostosuj wysokość, jeśli GPS pokazuje błędne dane (np. nad poziomem morza).',
    autoCalibrate: 'Auto-Kalibracja',
    calibrating: 'Kalibrowanie...',
    calibrationSuccess: 'Wysokość skalibrowana!',
    calibrationError: 'Błąd kalibracji',
    inAppBrowserWarning: 'Wykryto przeglądarkę wewnątrz aplikacji',
    inAppBrowserDesc: 'Przeglądarki wbudowane (Facebook, Messenger, Instagram, WhatsApp) często blokują GPS. Dla poprawnego działania otwórz tę stronę w Chrome, Safari, Opera lub Edge.',
    openInBrowser: 'Otwórz w przeglądarce',
    falls8g: 'Upadki 8g',
    falls5g: 'Upadki 5g',
    startTutorial: 'Uruchom Samouczek',
    tutorialSteps: [
      { title: 'Witaj', content: 'Witaj w Ski Tracker! Pozwól, że oprowadzimy Cię po aplikacji.' },
      { title: 'Śledzenie', content: 'Kliknij przycisk Play, aby rozpocząć śledzenie swojej sesji.' },
      { title: 'Statystyki', content: 'Przesuwaj karty statystyk, aby zobaczyć prędkość, wysokość i inne dane.' },
      { title: 'Mapa', content: 'Zobacz swoją aktualną pozycję i trasę na mapie.' },
      { title: 'Pokoje', content: 'Dołącz do pokoju lub stwórz własny, aby widzieć znajomych na mapie i rozmawiać z nimi.' },
      { title: 'Szukaj', content: 'Znajdź ośrodki narciarskie w pobliżu lub wyszukaj konkretne miejsca.' },
      { title: 'Ustawienia', content: 'Tutaj możesz zmienić język i inne opcje.' },
      { title: 'Centrowanie', content: 'Włącz tę opcję, aby mapa automatycznie podążała za Twoją pozycją.' }
    ],
    next: 'Dalej',
    finish: 'Zakończ',
    skip: 'Pomiń',
    searchResorts: 'Szukaj Ośrodków',
    searchPlaceholder: 'Szukaj ośrodka...',
    nearbyResorts: 'Pobliskie Ośrodki Narciarskie',
    noResortsFound: 'Nie znaleziono ośrodków w pobliżu.',
    searchingResorts: 'Szukanie ośrodków...',
    locationRequired: 'Lokalizacja jest wymagana do wyszukiwania w pobliżu.'
  }
};
import { motion, AnimatePresence } from 'motion/react';
import L from 'leaflet';
import { GeoPoint, SessionStats } from './types';
import { generateAppIcon } from './services/iconService';

// Fix Leaflet marker icons
// @ts-ignore
delete L.Icon.Default.prototype._getIconUrl;
L.Icon.Default.mergeOptions({
  iconRetinaUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/images/marker-icon-2x.png',
  iconUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/images/marker-icon.png',
  shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/images/marker-shadow.png',
});

// Helper to calculate distance between two points (Haversine formula)
const calculateDistance = (p1: { lat: number, lng: number }, p2: { lat: number, lng: number }) => {
  const R = 6371e3; // metres
  const φ1 = p1.lat * Math.PI / 180;
  const φ2 = p2.lat * Math.PI / 180;
  const Δφ = (p2.lat - p1.lat) * Math.PI / 180;
  const Δλ = (p2.lng - p1.lng) * Math.PI / 180;

  const a = Math.sin(Δφ / 2) * Math.sin(Δφ / 2) +
    Math.cos(φ1) * Math.cos(φ2) *
    Math.sin(Δλ / 2) * Math.sin(Δλ / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

  return R * c;
};

function MapUpdater({ center, follow }: { center: [number, number], follow: boolean }) {
  const map = useMap();
  
  useEffect(() => {
    // Fix for partial map loading - run once when map is ready
    const timer = setTimeout(() => {
      map.invalidateSize();
    }, 500);
    return () => clearTimeout(timer);
  }, [map]);

  useEffect(() => {
    if (follow) {
      map.setView(center, map.getZoom(), { animate: true });
    }
  }, [center, map, follow]);
  return null;
}

export default function App() {
  const [isTracking, setIsTracking] = useState(false);
  const [route, setRoute] = useState<GeoPoint[]>([]);
  const [currentPos, setCurrentPos] = useState<[number, number] | null>(null);
  const [isLocating, setIsLocating] = useState(false);
  const [locationError, setLocationError] = useState<string | null>(null);
  const [permissionStatus, setPermissionStatus] = useState<PermissionState | 'unknown'>('unknown');
  const [hasStarted, setHasStarted] = useState(false);
  const [followUser, setFollowUser] = useState(true);
  const [stats, setStats] = useState<SessionStats>({
    distance: 0,
    maxSpeed: 0,
    avgSpeed: 0,
    totalTime: 0,
    elevationGain: 0,
    elevationLoss: 0,
    currentSlope: 0,
    maxAltitude: -Infinity,
    maxSlope: -Infinity,
    minSlope: Infinity,
    falls8g: 0,
    falls5g: 0
  });
  const [startTime, setStartTime] = useState<number | null>(null);
  const [elapsedTime, setElapsedTime] = useState(0);
  const [appIcon, setAppIcon] = useState<string | null>(null);
  const [isGeneratingIcon, setIsGeneratingIcon] = useState(false);
  const [showSearchPanel, setShowSearchPanel] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [resorts, setResorts] = useState<any[]>([]);
  const [isSearchingResorts, setIsSearchingResorts] = useState(false);
  const [searchError, setSearchError] = useState<string | null>(null);
  const [hasApiKey, setHasApiKey] = useState(true);

  useEffect(() => {
    const checkKey = async () => {
      if (window.aistudio?.hasSelectedApiKey) {
        const hasKey = await window.aistudio.hasSelectedApiKey();
        setHasApiKey(hasKey);
      }
    };
    checkKey();
  }, [showSearchPanel]);

  useEffect(() => {
    if (showSearchPanel && resorts.length === 0 && currentPos && !isSearchingResorts && hasApiKey) {
      searchResorts();
    }
  }, [showSearchPanel, currentPos, resorts.length, hasApiKey]);
  const [language, setLanguage] = useState<Language>('pl');
  const [showSettings, setShowSettings] = useState(false);
  const [altitudeOffset, setAltitudeOffset] = useState(0);
  const [isInAppBrowser, setIsInAppBrowser] = useState(false);
  const hasCalibrated = useRef(false);
  const lastAltitudes = useRef<number[]>([]);
  const [showRoomModal, setShowRoomModal] = useState(false);
  const [roomName, setRoomName] = useState('');
  const [roomPassword, setRoomPassword] = useState('');
  const [userName, setUserName] = useState('');
  const [joinedRoom, setJoinedRoom] = useState<string | null>(null);
  const [otherUsers, setOtherUsers] = useState<Map<string, { name: string, lat: number, lng: number }>>(new Map());
  const [isJoiningRoom, setIsJoiningRoom] = useState(false);
  const [roomFeedback, setRoomFeedback] = useState<{ type: 'success' | 'error', msg: string } | null>(null);
  const [roomTab, setRoomTab] = useState<'join' | 'create'>('join');
  const [isMicActive, setIsMicActive] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [audioBlocked, setAudioBlocked] = useState(false);
  const [activeStatsPage, setActiveStatsPage] = useState(0);
  const [showTutorial, setShowTutorial] = useState(false);
  const [tutorialStep, setTutorialStep] = useState(0);
  const [tooltipPos, setTooltipPos] = useState<{ top?: number, left?: number, bottom?: number, right?: number, arrow?: 'top' | 'bottom' | 'left' | 'right' | 'center' }>({ arrow: 'center' });
  const [highlightRect, setHighlightRect] = useState<{ top: number, left: number, width: number, height: number } | null>(null);

  // Tutorial positioning logic
  useEffect(() => {
    if (!showTutorial) return;

    const targets = [
      null, // Welcome
      'tutorial-tracking',
      'tutorial-stats',
      'tutorial-map',
      'tutorial-rooms',
      'tutorial-search',
      'tutorial-settings',
      'tutorial-follow'
    ];

    const targetId = targets[tutorialStep];
    if (!targetId) {
      setTooltipPos({ top: window.innerHeight / 2, left: window.innerWidth / 2, arrow: 'center' });
      setHighlightRect(null);
      return;
    }

    const updatePos = () => {
      const el = document.getElementById(targetId);
      if (!el) {
        setHighlightRect(null);
        return;
      }

      const rect = el.getBoundingClientRect();
      if (targetId === 'tutorial-map') {
        setHighlightRect(null);
      } else {
        setHighlightRect({ top: rect.top, left: rect.left, width: rect.width, height: rect.height });
      }
      const padding = 16;
      const centerX = rect.left + rect.width / 2;
      const centerY = rect.top + rect.height / 2;

      if (targetId === 'tutorial-stats') {
        setTooltipPos({ 
          top: rect.bottom + padding, 
          left: centerX, 
          bottom: undefined, 
          right: undefined, 
          arrow: 'top' 
        });
      } else if (targetId === 'tutorial-tracking') {
        setTooltipPos({ 
          top: undefined, 
          left: centerX, 
          bottom: (window.innerHeight - rect.top) + padding, 
          right: undefined, 
          arrow: 'bottom' 
        });
      } else if (targetId === 'tutorial-rooms' || targetId === 'tutorial-settings' || targetId === 'tutorial-follow' || targetId === 'tutorial-search') {
        setTooltipPos({ 
          top: centerY, 
          left: undefined, 
          bottom: undefined, 
          right: (window.innerWidth - rect.left) + padding, 
          arrow: 'right' 
        });
      } else if (targetId === 'tutorial-map') {
        setTooltipPos({ 
          top: window.innerHeight / 2, 
          left: window.innerWidth / 2, 
          bottom: undefined, 
          right: undefined, 
          arrow: 'center' 
        });
      }
    };

    updatePos();
    window.addEventListener('resize', updatePos);
    return () => window.removeEventListener('resize', updatePos);
  }, [showTutorial, tutorialStep]);

  const socketRef = useRef<Socket | null>(null);
  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const audioStreamRef = useRef<MediaStream | null>(null);
  const audioContextRef = useRef<AudioContext | null>(null);
  const analyserRef = useRef<AnalyserNode | null>(null);
  const animationFrameRef = useRef<number | null>(null);
  const audioQueueRef = useRef<{ blob: Blob, mimeType: string }[]>([]);
  const isPlayingAudioRef = useRef(false);
  const recorderIntervalRef = useRef<number | null>(null);
  const t = translations[language];
  
  const watchId = useRef<number | null>(null);
  const timerInterval = useRef<NodeJS.Timeout | null>(null);
  const statsRef = useRef<SessionStats>(stats);
  const routeRef = useRef<GeoPoint[]>([]);
  const startTimeRef = useRef<number | null>(null);

  // Detect in-app browser
  useEffect(() => {
    const ua = navigator.userAgent || navigator.vendor || (window as any).opera;
    const isInApp = 
      /FBAN|FBAV|Messenger|Instagram|WhatsApp|TikTok|Snapchat|Pinterest|LinkedInApp/i.test(ua);
    
    if (isInApp) {
      setIsInAppBrowser(true);
    }
  }, []);

  const lastFallTime = useRef<number>(0);
  const lastWeightlessTime = useRef<number>(0);

  const [showFallAlert, setShowFallAlert] = useState(false);

  // Fall detection logic
  useEffect(() => {
    if (!isTracking) return;

    const handleMotion = (event: DeviceMotionEvent) => {
      const acc = event.accelerationIncludingGravity;
      if (!acc) return;

      const x = acc.x || 0;
      const y = acc.y || 0;
      const z = acc.z || 0;

      // Calculate total acceleration magnitude
      const magnitude = Math.sqrt(x * x + y * y + z * z);
      
      const now = Date.now();

      // 1. Detect weightlessness (free fall phase)
      // Normal gravity is ~9.8. If < 4.0, we are likely falling or in the air.
      if (magnitude < 4.0) {
        lastWeightlessTime.current = now;
      }

      // 2. Detect impact
      // Thresholds: 5g (50 m/s2) and 8g (80 m/s2)
      const THRESHOLD_8G = 80; 
      const THRESHOLD_5G = 50;

      // Fall is detected if:
      // - Magnitude exceeds threshold
      // - It's been at least 2s since last fall
      // - There was a "weightless" moment in the last 500ms (filters out hand waves)
      if (magnitude > THRESHOLD_5G && 
          now - lastFallTime.current > 2000 && 
          now - lastWeightlessTime.current < 500) {
        
        lastFallTime.current = now;
        // Haptic feedback for any fall
        if ('vibrate' in navigator) {
          navigator.vibrate([100, 50, 100]);
        }
        
        setShowFallAlert(true);
        setTimeout(() => setShowFallAlert(false), 3000);

        setStats(prev => {
          const newStats = { ...prev };
          if (magnitude > THRESHOLD_8G) {
            newStats.falls8g = (prev.falls8g || 0) + 1;
          } else {
            newStats.falls5g = (prev.falls5g || 0) + 1;
          }
          return newStats;
        });
      }
    };

    window.addEventListener('devicemotion', handleMotion);
    return () => window.removeEventListener('devicemotion', handleMotion);
  }, [isTracking]);

  // Sync refs with state for tracking logic
  useEffect(() => {
    statsRef.current = stats;
  }, [stats]);

  useEffect(() => {
    routeRef.current = route;
  }, [route]);

  useEffect(() => {
    startTimeRef.current = startTime;
  }, [startTime]);

  // Start/Stop Tracking
  const handleAutoCalibrate = async (lat: number, lng: number, currentAltitude: number) => {
    if (hasCalibrated.current) return;
    try {
      const resp = await fetch(`https://api.open-elevation.com/api/v1/lookup?locations=${lat},${lng}`);
      const data = await resp.json();
      if (data.results && data.results[0]) {
        const groundElevation = data.results[0].elevation;
        if (currentAltitude !== 0) {
          const offset = Math.round(groundElevation - currentAltitude);
          setAltitudeOffset(offset);
        } else {
          setAltitudeOffset(Math.round(groundElevation));
        }
        hasCalibrated.current = true;
      }
    } catch (err) {
      console.error("Auto-calibration error:", err);
    }
  };

  const handleStatsScroll = (e: React.UIEvent<HTMLDivElement>) => {
    const container = e.currentTarget;
    const scrollLeft = container.scrollLeft;
    const width = container.offsetWidth;
    const page = Math.round(scrollLeft / width);
    setActiveStatsPage(page);
  };

  const toggleTracking = useCallback(() => {
    if (isTracking) {
      // Stop
      if (watchId.current !== null) {
        navigator.geolocation.clearWatch(watchId.current);
        watchId.current = null;
      }
      if (timerInterval.current) {
        clearInterval(timerInterval.current);
      }
      setIsTracking(false);
    } else {
      // Start
      setIsTracking(true);
      hasCalibrated.current = false;
      const now = Date.now();
      setStartTime(now);
      startTimeRef.current = now;
      setRoute([]);
      routeRef.current = [];
      setElapsedTime(0);
      const initialStats = {
        distance: 0,
        maxSpeed: 0,
        avgSpeed: 0,
        totalTime: 0,
        elevationGain: 0,
        elevationLoss: 0,
        currentSlope: 0,
        maxAltitude: -Infinity,
        maxSlope: -Infinity,
        minSlope: Infinity,
        falls8g: 0,
        falls5g: 0
      };
      setStats(initialStats);
      statsRef.current = initialStats;
      
      timerInterval.current = setInterval(() => {
        setElapsedTime(prev => prev + 1000);
      }, 1000);

      watchId.current = navigator.geolocation.watchPosition(
        (position) => {
          const { latitude, longitude, speed, altitude } = position.coords;
          
          // Auto-calibrate on first valid point
          if (!hasCalibrated.current && altitude !== null) {
            handleAutoCalibrate(latitude, longitude, altitude);
          }

          // Simple smoothing for altitude
          let smoothedAltitude = altitude || 0;
          if (altitude !== null) {
            lastAltitudes.current.push(altitude);
            if (lastAltitudes.current.length > 5) lastAltitudes.current.shift();
            smoothedAltitude = lastAltitudes.current.reduce((a, b) => a + b, 0) / lastAltitudes.current.length;
          }

          const newPoint: GeoPoint = {
            lat: latitude,
            lng: longitude,
            timestamp: position.timestamp,
            speed: speed || 0,
            altitude: smoothedAltitude
          };

          setCurrentPos([latitude, longitude]);
          
          const lastPoint = routeRef.current[routeRef.current.length - 1];
          if (lastPoint) {
            const d = calculateDistance(lastPoint, newPoint);
            // Only add if moved more than 2 meters to avoid jitter
            if (d > 2) {
              const currentStats = statsRef.current;
              const newDistance = currentStats.distance + d;
              const newMaxSpeed = Math.max(currentStats.maxSpeed, speed || 0);
              
              let elevationGain = currentStats.elevationGain;
              let elevationLoss = currentStats.elevationLoss;
              let currentSlope = currentStats.currentSlope;
              let maxSlope = currentStats.maxSlope;
              let minSlope = currentStats.minSlope;
              
              if (altitude !== null && lastPoint.altitude !== null) {
                const diff = altitude - lastPoint.altitude;
                if (diff > 0.5) elevationGain += diff; // Filter small noise
                if (diff < -0.5) elevationLoss += Math.abs(diff);
                
                // Calculate slope: (elevation change / distance) * 100
                // We show "spadek" (descent) as positive, so use (last - current)
                const slopeVal = ((lastPoint.altitude - altitude) * 100) / d;
                currentSlope = slopeVal;
                
                // Track max and min slope (descent)
                // Only track if moving (speed > 1 m/s) to avoid noise at standstill
                if ((speed || 0) > 1) {
                  maxSlope = Math.max(maxSlope, slopeVal);
                  minSlope = Math.min(minSlope, slopeVal);
                }
              }
              
              const updatedStats = {
                ...currentStats,
                distance: newDistance,
                maxSpeed: newMaxSpeed,
                elevationGain,
                elevationLoss,
                currentSlope,
                maxSlope,
                minSlope,
                maxAltitude: Math.max(currentStats.maxAltitude, smoothedAltitude),
                avgSpeed: newDistance / ((Date.now() - (startTimeRef.current || Date.now())) / 1000)
              };

              setStats(updatedStats);
              statsRef.current = updatedStats;
              setRoute(prev => [...prev, newPoint]);
              routeRef.current = [...routeRef.current, newPoint];
            }
          } else {
            const initialPointStats = {
              ...statsRef.current,
              maxAltitude: smoothedAltitude
            };
            setStats(initialPointStats);
            statsRef.current = initialPointStats;
            setRoute([newPoint]);
            routeRef.current = [newPoint];
          }
        },
        (error) => {
          console.error("Geolocation watch error:", error);
          // If high accuracy fails during tracking, we don't stop, 
          // but we log it. Most browsers will fallback automatically 
          // or keep trying.
        },
        { 
          enableHighAccuracy: true,
          timeout: 15000,
          maximumAge: 0
        }
      );
    }
  }, [isTracking]);

  // Initial position
  const getInitialLocation = useCallback(async () => {
    if (!navigator.geolocation) {
      setLocationError("Twoje urządzenie nie obsługuje geolokalizacji.");
      return;
    }

    setIsLocating(true);
    setLocationError(null);
    setHasStarted(true);

    // Check permission status if API is available
    if ('permissions' in navigator) {
      try {
        const status = await navigator.permissions.query({ name: 'geolocation' });
        setPermissionStatus(status.state);
        status.onchange = () => setPermissionStatus(status.state);
      } catch (e) {
        console.warn("Permissions API not supported for geolocation");
      }
    }

    const options: PositionOptions = {
      enableHighAccuracy: true,
      timeout: 15000,
      maximumAge: 0
    };

    // Request motion permission for iOS
    if (typeof (DeviceMotionEvent as any).requestPermission === 'function') {
      try {
        const response = await (DeviceMotionEvent as any).requestPermission();
        if (response !== 'granted') {
          console.warn('Motion permission not granted');
        }
      } catch (e) {
        console.error('Error requesting motion permission:', e);
      }
    }

    const onSuccess = (pos: GeolocationPosition) => {
      setCurrentPos([pos.coords.latitude, pos.coords.longitude]);
      setIsLocating(false);
      setPermissionStatus('granted');
    };

    const onError = (err: GeolocationPositionError) => {
      console.error("Initial location error:", err);
      
      // If high accuracy failed, try one more time with low accuracy
      if (err.code === err.TIMEOUT || err.code === err.POSITION_UNAVAILABLE) {
        navigator.geolocation.getCurrentPosition(
          onSuccess,
          (err2) => {
            setIsLocating(false);
            setLocationError(t.gpsSignalWeak);
          },
          { ...options, enableHighAccuracy: false, timeout: 10000 }
        );
      } else {
        setIsLocating(false);
        let msg = t.gpsError;
        if (err.code === 1) {
          msg = t.gpsPermissionDenied;
          setPermissionStatus('denied');
        } else if (err.code === 2) {
          msg = t.gpsSignalWeak;
        } else if (err.code === 3) {
          msg = t.gpsTimeout;
        }
        setLocationError(msg);
      }
    };

    navigator.geolocation.getCurrentPosition(onSuccess, onError, options);
  }, [t]);

  // No auto-start to avoid browser blocking
  useEffect(() => {
    // Just check permission status without requesting
    if ('permissions' in navigator) {
      navigator.permissions.query({ name: 'geolocation' })
        .then(status => setPermissionStatus(status.state))
        .catch(() => {});
    }
  }, []);

  // WebSocket setup
  useEffect(() => {
    socketRef.current = io();

    socketRef.current.on('connect_error', () => {
      setIsJoiningRoom(false);
      setRoomFeedback({ type: 'error', msg: 'Connection error' });
    });

    socketRef.current.on('user-location-update', ({ id, lat, lng }) => {
      setOtherUsers(prev => {
        const next = new Map(prev);
        const user = next.get(id) as { name: string, lat: number, lng: number } | undefined;
        if (user) {
          next.set(id, { name: user.name, lat, lng });
        }
        return next;
      });
    });

    socketRef.current.on('room-users', (users: any[]) => {
      const usersMap = new Map();
      users.forEach(u => {
        if (u.id !== socketRef.current?.id) {
          usersMap.set(u.id, { name: u.name, lat: u.lat, lng: u.lng });
        }
      });
      setOtherUsers(usersMap);
    });

    socketRef.current.on('user-left', (id: string) => {
      setOtherUsers(prev => {
        const next = new Map(prev);
        next.delete(id);
        return next;
      });
    });

    socketRef.current.on('audio-stream', async ({ audio, mimeType }: { audio: ArrayBuffer, mimeType: string }) => {
      const blob = new Blob([audio], { type: mimeType });
      audioQueueRef.current.push({ blob, mimeType });
      playNextAudio();
    });

    socketRef.current.on('joined-room', ({ roomName }) => {
      setJoinedRoom(roomName);
      setIsJoiningRoom(false);
      const currentT = translations[language];
      const successMsg = roomTab === 'create' ? currentT.roomCreatedSuccess : currentT.roomJoinedSuccess;
      setRoomFeedback({ type: 'success', msg: successMsg });
      setTimeout(() => setRoomFeedback(null), 3000);
    });

    socketRef.current.on('error', (msg: string) => {
      setIsJoiningRoom(false);
      const currentT = translations[language];
      let errorMsg = msg;
      if (msg === 'Invalid password') errorMsg = currentT.invalidPassword;
      else if (msg === 'Room already exists') errorMsg = currentT.roomAlreadyExists;
      else if (msg === 'Room does not exist') errorMsg = currentT.roomDoesNotExist;
      else if (msg === 'Internal server error') errorMsg = currentT.internalError;
      
      setRoomFeedback({ type: 'error', msg: errorMsg });
    });

    return () => {
      socketRef.current?.disconnect();
    };
  }, [language]); // Re-bind listeners when language changes to use correct translations in feedback

  // Update location in room
  useEffect(() => {
    if (joinedRoom && currentPos && socketRef.current) {
      socketRef.current.emit('update-location', {
        roomName: joinedRoom,
        lat: currentPos[0],
        lng: currentPos[1]
      });
    }
  }, [currentPos, joinedRoom]);

  const joinRoom = () => {
    if (!roomName || !roomPassword || !userName) return;
    setIsJoiningRoom(true);
    setRoomFeedback(null);
    socketRef.current?.emit('join-room', { 
      roomName, 
      password: roomPassword, 
      userName,
      isCreating: roomTab === 'create'
    });
  };

  const leaveRoom = () => {
    socketRef.current?.emit('leave-room');
    setJoinedRoom(null);
    setOtherUsers(new Map());
    if (isMicActive) stopRecording();
  };

  const playNextAudio = async () => {
    if (isPlayingAudioRef.current || audioQueueRef.current.length === 0) return;

    isPlayingAudioRef.current = true;
    const item = audioQueueRef.current.shift();
    if (!item) {
      isPlayingAudioRef.current = false;
      return;
    }

    const url = URL.createObjectURL(item.blob);
    const audio = new Audio(url);
    
    audio.onended = () => {
      URL.revokeObjectURL(url);
      isPlayingAudioRef.current = false;
      playNextAudio();
    };

    try {
      await audio.play();
      setAudioBlocked(false);
    } catch (err) {
      console.error("Audio playback error:", err);
      // If blocked by autoplay, show a button
      if (err instanceof Error && err.name === 'NotAllowedError') {
        setAudioBlocked(true);
      }
      isPlayingAudioRef.current = false;
      // Don't retry immediately if blocked to avoid infinite loop
      if (!audioBlocked) playNextAudio();
    }
  };

  const startRecording = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      audioStreamRef.current = stream;
      
      // Setup Analyser for voice activity visualization
      const audioContext = new (window.AudioContext || (window as any).webkitAudioContext)();
      audioContextRef.current = audioContext;
      const source = audioContext.createMediaStreamSource(stream);
      const analyser = audioContext.createAnalyser();
      analyser.fftSize = 256;
      source.connect(analyser);
      analyserRef.current = analyser;

      const bufferLength = analyser.frequencyBinCount;
      const dataArray = new Uint8Array(bufferLength);

      const checkVolume = () => {
        if (!analyserRef.current) return;
        analyserRef.current.getByteFrequencyData(dataArray);
        let sum = 0;
        for (let i = 0; i < bufferLength; i++) {
          sum += dataArray[i];
        }
        const average = sum / bufferLength;
        setIsSpeaking(average > 30); // Threshold for speaking
        animationFrameRef.current = requestAnimationFrame(checkVolume);
      };
      checkVolume();

      const mimeType = MediaRecorder.isTypeSupported('audio/webm; codecs=opus') 
        ? 'audio/webm; codecs=opus' 
        : MediaRecorder.isTypeSupported('audio/ogg; codecs=opus')
          ? 'audio/ogg; codecs=opus'
          : 'audio/mp4';
      
      const createRecorder = () => {
        const mediaRecorder = new MediaRecorder(stream, { mimeType });
        mediaRecorderRef.current = mediaRecorder;

        mediaRecorder.ondataavailable = async (event) => {
          if (event.data.size > 0 && socketRef.current && joinedRoom) {
            const buffer = await event.data.arrayBuffer();
            socketRef.current.emit('audio-data', {
              roomName: joinedRoom,
              audio: buffer,
              mimeType
            });
          }
        };

        mediaRecorder.start();
      };

      // Use a cycle of stop/start to create standalone playable chunks
      createRecorder();
      recorderIntervalRef.current = window.setInterval(() => {
        if (mediaRecorderRef.current && mediaRecorderRef.current.state === 'recording') {
          mediaRecorderRef.current.stop();
          createRecorder();
        }
      }, 1000); // 1 second chunks

      setIsMicActive(true);
      setAudioBlocked(false); // Interaction happened
    } catch (err) {
      console.error("Microphone access error:", err);
      alert("Błąd dostępu do mikrofonu. Upewnij się, że udzieliłeś uprawnień w przeglądarce.");
    }
  };

  const stopRecording = () => {
    if (recorderIntervalRef.current) {
      clearInterval(recorderIntervalRef.current);
      recorderIntervalRef.current = null;
    }
    if (animationFrameRef.current) {
      cancelAnimationFrame(animationFrameRef.current);
    }
    if (mediaRecorderRef.current && mediaRecorderRef.current.state !== 'inactive') {
      mediaRecorderRef.current.stop();
    }
    if (audioStreamRef.current) {
      audioStreamRef.current.getTracks().forEach(track => track.stop());
    }
    if (audioContextRef.current) {
      audioContextRef.current.close();
    }
    setIsMicActive(false);
    setIsSpeaking(false);
  };

  const toggleMic = () => {
    if (isMicActive) {
      stopRecording();
    } else {
      startRecording();
    }
  };

  const searchResorts = async (query?: string) => {
    setIsSearchingResorts(true);
    setSearchError(null);
    try {
      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey) {
        throw new Error(language === 'pl' ? "Brak klucza API Gemini. Sprawdź konfigurację platformy." : "Gemini API Key missing. Check platform configuration.");
      }
      const ai = new GoogleGenAI({ apiKey });
      const prompt = query 
        ? `Find ski resorts matching "${query}"` 
        : "Find popular ski resorts near my location";
      
      const config: any = {
        tools: [{ googleMaps: {} }]
      };

      if (currentPos) {
        config.toolConfig = {
          retrievalConfig: {
            latLng: {
              latitude: currentPos[0],
              longitude: currentPos[1]
            }
          }
        };
      }

      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config
      });

      const metadata = response.candidates?.[0]?.groundingMetadata;
      const chunks = metadata?.groundingChunks;
      
      if (chunks && chunks.length > 0) {
        const foundResorts = chunks
          .filter((c: any) => c.maps || c.web)
          .map((c: any) => ({
            title: c.maps?.title || c.web?.title || "Ski Resort",
            uri: c.maps?.uri || c.web?.uri
          }))
          .filter((r: any) => r.uri);
        
        if (foundResorts.length > 0) {
          setResorts(foundResorts);
          return;
        }
      }
      
      // Fallback: if no chunks but there is text, maybe we can't parse it as resorts
      // but at least we know the model responded.
      setResorts([]);
    } catch (error: any) {
      console.error("Failed to search resorts:", error);
      if (error.message?.includes("Requested entity was not found") || error.message?.includes("API Key missing")) {
        setHasApiKey(false);
      }
      setSearchError(error.message || "Failed to find resorts");
      setResorts([]);
    } finally {
      setIsSearchingResorts(false);
    }
  };

  const handleSelectKey = async () => {
    if (window.aistudio?.openSelectKey) {
      await window.aistudio.openSelectKey();
      setHasApiKey(true);
      searchResorts(searchQuery);
    }
  };

  const centerMap = () => {
    if (currentPos) {
      setFollowUser(true);
    }
  };

  const formatTime = (ms: number) => {
    const seconds = Math.floor((ms / 1000) % 60);
    const minutes = Math.floor((ms / (1000 * 60)) % 60);
    const hours = Math.floor(ms / (1000 * 60 * 60));
    return `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
  };

  const formatSpeed = (ms: number) => (ms * 3.6).toFixed(1); // m/s to km/h

  const handleGenerateIcon = async () => {
    setIsGeneratingIcon(true);
    try {
      const icon = await generateAppIcon();
      setAppIcon(icon);
    } catch (error) {
      console.error("Failed to generate icon:", error);
    } finally {
      setIsGeneratingIcon(false);
    }
  };

  return (
    <div className="relative flex flex-col h-screen bg-zinc-950 overflow-hidden">
      {/* Header */}
      <header className="flex items-center justify-between px-4 py-3 border-b border-zinc-800 bg-zinc-900/80 backdrop-blur-md z-50">
        <div className="flex items-center gap-2">
          <div className="p-1.5 bg-emerald-500/10 rounded-lg">
            <Mountain className="w-5 h-5 text-emerald-500" />
          </div>
          <div>
            <h1 className="text-base font-bold tracking-tight">SkiTrack</h1>
          </div>
        </div>
        <div className="flex items-center gap-4">
          <div className="flex flex-col items-end border-r border-zinc-800 pr-4">
            <span className="text-[10px] text-zinc-500 font-mono uppercase leading-none mb-1">{t.speed}</span>
            <div className="flex items-baseline gap-1">
              <span className="text-lg font-mono font-bold text-zinc-100 leading-none">
                {formatSpeed(route[route.length - 1]?.speed || 0)}
              </span>
              <span className="text-[9px] text-zinc-500 font-medium">km/h</span>
            </div>
          </div>
          <div className="flex flex-col items-end">
            <span className="text-[10px] text-zinc-500 font-mono uppercase leading-none mb-1">{t.altitude}</span>
            <div className="flex items-baseline gap-1">
              <span className="text-lg font-mono font-bold text-emerald-400 leading-none">
                {((route[route.length - 1]?.altitude || 0) + altitudeOffset).toFixed(0)}
              </span>
              <span className="text-[9px] text-zinc-500 font-medium">m</span>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 relative">
        {/* Loading / Error / Start States */}
        {(!hasStarted || isLocating || locationError) && (
          <div className="absolute inset-0 z-[60] bg-zinc-950 flex flex-col items-center justify-center p-8 text-center">
            {!hasStarted ? (
              <>
                <div className="p-6 bg-emerald-500/10 rounded-full mb-6">
                  <Navigation className="w-12 h-12 text-emerald-500" />
                </div>
                <h2 className="text-2xl font-bold text-zinc-100 mb-3">{t.requiredLocation}</h2>
                <p className="text-zinc-400 mb-8 max-w-xs">
                  {t.locationDesc}
                </p>

                {isInAppBrowser && (
                  <div className="mb-8 p-4 bg-amber-500/10 border border-amber-500/20 rounded-2xl text-left">
                    <div className="flex items-center gap-3 mb-2 text-amber-500">
                      <Globe className="w-5 h-5" />
                      <span className="font-bold text-sm">{t.inAppBrowserWarning}</span>
                    </div>
                    <p className="text-xs text-zinc-400 leading-relaxed">
                      {t.inAppBrowserDesc}
                    </p>
                  </div>
                )}
                
                <button 
                  onClick={getInitialLocation}
                  className="w-full max-w-xs py-4 bg-emerald-500 hover:bg-emerald-600 text-white rounded-2xl font-bold text-lg transition-all shadow-xl shadow-emerald-500/20"
                >
                  {t.shareLocation}
                </button>
              </>
            ) : isLocating ? (
              <>
                <div className="w-12 h-12 border-4 border-emerald-500/20 border-t-emerald-500 rounded-full animate-spin mb-4" />
                <p className="text-zinc-400 font-medium tracking-wide">{t.searching}</p>
                <p className="text-zinc-500 text-sm mt-2">{t.gpsSignalWeak}</p>
              </>
            ) : (
              <>
                <div className="p-4 bg-red-500/10 rounded-full mb-4">
                  <Activity className="w-8 h-8 text-red-500" />
                </div>
                <h2 className="text-xl font-bold text-zinc-100 mb-2">
                  {permissionStatus === 'denied' ? t.noPermission : t.gpsError}
                </h2>
                <p className="text-zinc-400 mb-6 max-w-xs">{locationError}</p>
                <button 
                  onClick={getInitialLocation}
                  className="px-8 py-4 bg-emerald-500 hover:bg-emerald-600 text-white rounded-2xl font-bold transition-all shadow-xl shadow-emerald-500/20"
                >
                  {t.tryAgain}
                </button>
                <p className="text-zinc-500 text-xs mt-6 max-w-[240px]">
                  Jeśli używasz aplikacji APK, upewnij się, że przy jej tworzeniu zaznaczono uprawnienia GPS (ACCESS_FINE_LOCATION).
                </p>
              </>
            )}
          </div>
        )}

        {/* Map Container */}
        <div id="tutorial-map" className="absolute inset-0 z-0">
          {currentPos && (
            <MapContainer 
              center={currentPos} 
              zoom={15} 
              zoomControl={false}
              className="w-full h-full"
              preferCanvas={true}
            >
              <TileLayer
                url="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
                attribution='Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community'
              />
              <TileLayer
                url={`https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}`}
                attribution='Labels &copy; Esri &mdash; Source: Esri, DeLorme, NAVTEQ, TomTom, and others'
                zIndex={1000}
              />
              <TileLayer
                url="https://tile.waymarkedtrails.org/slopes/{z}/{x}/{y}.png"
                attribution='&copy; <a href="https://slopes.waymarkedtrails.org">Waymarked Trails</a>'
                zIndex={900}
                opacity={0.8}
              />
              <MapUpdater center={currentPos} follow={followUser} />
              
              {route.length > 1 && (
                <Polyline 
                  positions={route.map(p => [p.lat, p.lng])} 
                  color="#ef4444" 
                  weight={6}
                  opacity={1}
                />
              )}
              
              {currentPos && (
                <CircleMarker 
                  center={currentPos} 
                  radius={8}
                  pathOptions={{ fillColor: '#ef4444', fillOpacity: 1, color: 'white', weight: 3 }}
                />
              )}

              {Array.from(otherUsers.entries()).map(([id, user]) => (
                user.lat !== 0 && (
                  <Marker 
                    key={id} 
                    position={[user.lat, user.lng]}
                    icon={L.divIcon({
                      className: 'custom-div-icon',
                      html: `<div class="flex flex-col items-center">
                        <div class="bg-emerald-500 text-white text-[10px] font-bold px-1.5 py-0.5 rounded shadow-lg whitespace-nowrap mb-1 border border-white/20">${user.name}</div>
                        <div class="w-3 h-3 bg-emerald-500 rounded-full border-2 border-white shadow-lg"></div>
                      </div>`,
                      iconSize: [0, 0],
                      iconAnchor: [0, 0]
                    })}
                  />
                )
              ))}
            </MapContainer>
          )}
        </div>

        {/* Stats Overlay - Top */}
        <div id="tutorial-stats" className="absolute top-3 left-0 right-0 z-10 px-2 group">
          <div 
            onScroll={handleStatsScroll}
            className="overflow-x-auto scrollbar-hide snap-x snap-mandatory flex gap-1 pb-1"
          >
            <div className="flex-shrink-0 w-[32.5%] snap-start">
              <StatCard 
                label={t.distance} 
                value={(stats.distance / 1000).toFixed(2)} 
                unit="km" 
                icon={<Navigation className="w-3.5 h-3.5" />} 
              />
            </div>
            <div className="flex-shrink-0 w-[32.5%]">
              <StatCard 
                label={t.avgSpeed} 
                value={formatSpeed(stats.avgSpeed)} 
                unit="km/h" 
                icon={<Activity className="w-3.5 h-3.5" />} 
              />
            </div>
            <div className="flex-shrink-0 w-[32.5%]">
              <StatCard 
                label={t.maxAltitude} 
                value={stats.maxAltitude === -Infinity || stats.maxAltitude === undefined ? "0" : (stats.maxAltitude + altitudeOffset).toFixed(0)} 
                unit="m" 
                icon={<TrendingUp className="w-3.5 h-3.5" />} 
              />
            </div>
            <div className="flex-shrink-0 w-[32.5%] snap-start">
              <StatCard 
                label={t.maxSpeed} 
                value={formatSpeed(stats.maxSpeed)} 
                unit="km/h" 
                icon={<Zap className="w-3.5 h-3.5" />} 
              />
            </div>
            <div className="flex-shrink-0 w-[32.5%]">
              <StatCard 
                label={t.slope} 
                value={stats.currentSlope?.toFixed(0) || "0"} 
                unit="%" 
                icon={<ArrowDownRight className="w-3.5 h-3.5" />} 
              />
            </div>
            <div className="flex-shrink-0 w-[32.5%]">
              <StatCard 
                label={t.maxSlope} 
                value={stats.maxSlope === -Infinity || stats.maxSlope === undefined ? "0" : stats.maxSlope.toFixed(0)} 
                unit="%" 
                icon={<ArrowDownRight className="w-3.5 h-3.5 text-red-500" />} 
              />
            </div>
            <div className="flex-shrink-0 w-[32.5%] snap-start">
              <StatCard 
                label={t.minSlope} 
                value={stats.minSlope === Infinity || stats.minSlope === undefined ? "0" : stats.minSlope.toFixed(0)} 
                unit="%" 
                icon={<ArrowUpRight className="w-3.5 h-3.5 text-emerald-500" />} 
              />
            </div>
            <div className="flex-shrink-0 w-[32.5%]">
              <StatCard 
                label={t.falls8g} 
                value={stats.falls8g.toString()} 
                unit="" 
                icon={<Activity className="w-3.5 h-3.5 text-red-600" />} 
              />
            </div>
            <div className="flex-shrink-0 w-[32.5%]">
              <StatCard 
                label={t.falls5g} 
                value={stats.falls5g.toString()} 
                unit="" 
                icon={<Activity className="w-3.5 h-3.5 text-orange-500" />} 
              />
            </div>
            {/* Spacer to allow last item to snap to start */}
            <div className="flex-shrink-0 w-[67.5%]" />
          </div>
          <div className="flex justify-center gap-1.5 mt-1">
            {[0, 1, 2].map((page) => (
              <div 
                key={page}
                className={`transition-all duration-300 rounded-full shadow-sm ring-1 ring-black/40 ${
                  activeStatsPage === page 
                    ? 'w-4 h-1.5 bg-emerald-400 shadow-emerald-500/20' 
                    : 'w-1.5 h-1.5 bg-white/60'
                }`}
              />
            ))}
          </div>
        </div>

        {/* Controls - Bottom */}
        <div className="absolute bottom-8 left-0 right-0 px-6 flex justify-center items-center gap-4 z-10">
          <motion.button
            id="tutorial-tracking"
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={toggleTracking}
            className={`flex-1 max-w-[240px] flex items-center justify-center gap-3 py-4 rounded-2xl font-bold text-lg shadow-2xl transition-colors ${
              isTracking 
                ? 'bg-red-500 text-white' 
                : 'bg-emerald-500 text-white'
            }`}
          >
            {isTracking ? (
              <div className="flex flex-col items-center">
                <div className="flex items-center gap-3">
                  <Square className="w-5 h-5 fill-current" />
                  <span>{t.stop}</span>
                </div>
                <span className="text-sm font-mono opacity-80 mt-1">{formatTime(elapsedTime)}</span>
              </div>
            ) : (
              <div className="flex flex-col items-center">
                <div className="flex items-center gap-3">
                  <Play className="w-5 h-5 fill-current" />
                  <span>{t.start}</span>
                </div>
                {elapsedTime > 0 && (
                  <span className="text-sm font-mono opacity-80 mt-1">{formatTime(elapsedTime)}</span>
                )}
              </div>
            )}
          </motion.button>
        </div>

        {/* Fall Alert */}
        <AnimatePresence>
          {showFallAlert && (
            <motion.div
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: 50 }}
              className="absolute bottom-24 left-1/2 -translate-x-1/2 z-[100] bg-red-500 text-white px-6 py-3 rounded-full font-bold shadow-2xl flex items-center gap-2"
            >
              <Activity className="w-5 h-5" />
              <span>{t.fallDetected}</span>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Side Controls */}
        <div className="absolute right-3 bottom-28 flex flex-col gap-2 z-10">
          {audioBlocked && (
            <motion.button
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              onClick={() => { setAudioBlocked(false); playNextAudio(); }}
              className="w-12 h-12 bg-red-500 text-white rounded-2xl flex items-center justify-center shadow-lg animate-bounce"
            >
              <Zap className="w-6 h-6" />
            </motion.button>
          )}
          {joinedRoom && (
            <IconButton 
              onClick={toggleMic}
              active={isMicActive}
              icon={
                <div className="relative">
                  {isMicActive ? <Mic className="w-5 h-5 text-emerald-500" /> : <MicOff className="w-5 h-5 text-zinc-400" />}
                  {isSpeaking && (
                    <div className="absolute -inset-1 border-2 border-emerald-500 rounded-full animate-ping opacity-50" />
                  )}
                </div>
              } 
            />
          )}
          <IconButton 
            id="tutorial-search"
            onClick={() => {
              setShowSearchPanel(true);
              if (resorts.length === 0) searchResorts();
            }}
            icon={<Search className="w-5 h-5 text-zinc-400" />} 
          />
          <IconButton 
            id="tutorial-rooms"
            onClick={() => setShowRoomModal(true)}
            active={!!joinedRoom}
            icon={<Users className={`w-5 h-5 ${joinedRoom ? 'text-emerald-500' : 'text-zinc-400'}`} />} 
          />
          <IconButton 
            id="tutorial-settings"
            onClick={() => setShowSettings(true)}
            icon={<SettingsIcon className="w-5 h-5" />} 
          />
          <IconButton 
            id="tutorial-follow"
            active={followUser}
            onClick={() => setFollowUser(!followUser)}
            icon={<Navigation className={`w-5 h-5 ${followUser ? 'text-emerald-500' : 'text-zinc-400'}`} />} 
          />
        </div>

        {/* Controls - Bottom */}

        {/* Room Modal */}
        <AnimatePresence>
          {showRoomModal && (
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 z-[80] bg-zinc-950/95 backdrop-blur-xl flex flex-col items-center justify-center p-6"
            >
              <div className="w-full max-w-sm bg-zinc-900 border border-zinc-800 rounded-3xl p-6 shadow-2xl">
                <div className="flex justify-between items-center mb-6">
                  <div className="flex items-center gap-3">
                    <div className="p-2 bg-emerald-500/10 rounded-lg">
                      <Users className="w-5 h-5 text-emerald-500" />
                    </div>
                    <h2 className="text-xl font-bold text-zinc-100">{t.room}</h2>
                  </div>
                  <button 
                    onClick={() => setShowRoomModal(false)}
                    className="p-2 hover:bg-zinc-800 rounded-full transition-colors"
                  >
                    <X className="w-6 h-6 text-zinc-500" />
                  </button>
                </div>

                {joinedRoom ? (
                  <div className="space-y-6">
                    {roomFeedback?.type === 'success' && (
                      <motion.div 
                        initial={{ opacity: 0, y: -10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="p-3 bg-emerald-500/10 border border-emerald-500/20 rounded-xl text-emerald-500 text-xs font-bold text-center"
                      >
                        {roomFeedback.msg}
                      </motion.div>
                    )}
                    <div className="p-4 bg-emerald-500/5 border border-emerald-500/20 rounded-2xl">
                      <p className="text-zinc-400 text-sm mb-1">{t.connectedToRoom}</p>
                      <p className="text-xl font-bold text-emerald-500">{joinedRoom}</p>
                    </div>

                    <div className="p-4 bg-zinc-800/50 border border-zinc-800 rounded-2xl">
                      <div className="flex items-center justify-between mb-3">
                        <h3 className="text-xs font-bold text-zinc-500 uppercase tracking-widest">{t.voiceChat}</h3>
                        <div className={`px-2 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-tighter ${isMicActive ? 'bg-emerald-500 text-white animate-pulse' : 'bg-zinc-700 text-zinc-400'}`}>
                          {isMicActive ? 'Live' : 'Off'}
                        </div>
                      </div>
                      <button 
                        onClick={toggleMic}
                        className={`w-full py-3 rounded-xl font-bold flex items-center justify-center gap-2 transition-all ${
                          isMicActive 
                            ? 'bg-emerald-500 text-white shadow-lg shadow-emerald-500/20' 
                            : 'bg-zinc-700 text-zinc-300 hover:bg-zinc-600'
                        }`}
                      >
                        {isMicActive ? <Mic className="w-5 h-5" /> : <MicOff className="w-5 h-5" />}
                        {isMicActive ? t.micOn : t.micOff}
                      </button>
                    </div>
                    
                    <div>
                      <h3 className="text-xs font-bold text-zinc-500 uppercase tracking-widest mb-3">{t.otherUsers} ({otherUsers.size})</h3>
                      <div className="space-y-2 max-h-40 overflow-y-auto pr-2 custom-scrollbar">
                        {Array.from(otherUsers.entries()).map(([id, user]) => {
                          const userData = user as { name: string, lat: number, lng: number };
                          return (
                            <div key={id} className="flex items-center gap-3 p-3 bg-zinc-800/50 rounded-xl border border-zinc-800">
                              <div className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse" />
                              <span className="text-zinc-200 font-medium">{userData.name}</span>
                            </div>
                          );
                        })}
                        {otherUsers.size === 0 && (
                          <p className="text-zinc-600 text-sm italic py-2">Brak innych osób w pokoju</p>
                        )}
                      </div>
                    </div>

                    <button 
                      onClick={leaveRoom}
                      className="w-full py-4 bg-red-500/10 hover:bg-red-500/20 text-red-500 border border-red-500/20 rounded-2xl font-bold transition-colors"
                    >
                      {t.leave}
                    </button>
                  </div>
                ) : (
                  <div className="space-y-4">
                    {/* Tabs */}
                    <div className="flex bg-zinc-800 p-1 rounded-2xl mb-6">
                      <button 
                        onClick={() => { setRoomTab('join'); setRoomFeedback(null); }}
                        className={`flex-1 py-2.5 rounded-xl font-bold text-sm transition-all ${
                          roomTab === 'join' ? 'bg-zinc-700 text-white shadow-lg' : 'text-zinc-500'
                        }`}
                      >
                        {t.joinRoom}
                      </button>
                      <button 
                        onClick={() => { setRoomTab('create'); setRoomFeedback(null); }}
                        className={`flex-1 py-2.5 rounded-xl font-bold text-sm transition-all ${
                          roomTab === 'create' ? 'bg-zinc-700 text-white shadow-lg' : 'text-zinc-500'
                        }`}
                      >
                        {t.createRoom}
                      </button>
                    </div>

                    <p className="text-zinc-400 text-sm mb-4">
                      {roomTab === 'join' ? t.joinRoom : t.createRoom}
                    </p>
                    
                    {roomFeedback?.type === 'error' && (
                      <motion.div 
                        initial={{ opacity: 0, y: -10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="p-3 bg-red-500/10 border border-red-500/20 rounded-xl text-red-500 text-xs font-bold text-center"
                      >
                        {roomFeedback.msg}
                      </motion.div>
                    )}

                    <div>
                      <label className="block text-[10px] font-bold text-zinc-500 uppercase tracking-wider mb-1.5 ml-1">{t.userName}</label>
                      <input 
                        type="text" 
                        value={userName}
                        onChange={(e) => setUserName(e.target.value)}
                        placeholder="np. Marek"
                        disabled={isJoiningRoom}
                        className="w-full bg-zinc-800 border border-zinc-700 rounded-xl py-3 px-4 text-zinc-100 focus:outline-none focus:border-emerald-500 transition-colors disabled:opacity-50"
                      />
                    </div>

                    <div>
                      <label className="block text-[10px] font-bold text-zinc-500 uppercase tracking-wider mb-1.5 ml-1">{t.roomName}</label>
                      <input 
                        type="text" 
                        value={roomName}
                        onChange={(e) => setRoomName(e.target.value)}
                        placeholder="Nazwa grupy"
                        disabled={isJoiningRoom}
                        className="w-full bg-zinc-800 border border-zinc-700 rounded-xl py-3 px-4 text-zinc-100 focus:outline-none focus:border-emerald-500 transition-colors disabled:opacity-50"
                      />
                    </div>

                    <div>
                      <label className="block text-[10px] font-bold text-zinc-500 uppercase tracking-wider mb-1.5 ml-1">{t.password}</label>
                      <input 
                        type="password" 
                        value={roomPassword}
                        onChange={(e) => setRoomPassword(e.target.value)}
                        placeholder="••••••"
                        disabled={isJoiningRoom}
                        className="w-full bg-zinc-800 border border-zinc-700 rounded-xl py-3 px-4 text-zinc-100 focus:outline-none focus:border-emerald-500 transition-colors disabled:opacity-50"
                      />
                    </div>

                    <button 
                      onClick={joinRoom}
                      disabled={!roomName || !roomPassword || !userName || isJoiningRoom}
                      className="w-full mt-4 py-4 bg-emerald-500 hover:bg-emerald-600 disabled:opacity-50 disabled:hover:bg-emerald-500 text-white rounded-2xl font-bold text-lg transition-all shadow-xl shadow-emerald-500/20 flex items-center justify-center gap-2"
                    >
                      {isJoiningRoom ? (
                        <>
                          <div className="w-5 h-5 border-2 border-white/20 border-t-white rounded-full animate-spin" />
                          {t.joiningRoom}
                        </>
                      ) : (
                        roomTab === 'create' ? t.createRoom : t.join
                      )}
                    </button>
                  </div>
                )}

                <button 
                  onClick={() => setShowRoomModal(false)}
                  className="w-full mt-4 py-3 text-zinc-500 hover:text-zinc-300 font-medium transition-colors"
                >
                  {t.close}
                </button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Search Resorts Modal */}
        <AnimatePresence>
          {showSearchPanel && (
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 z-[85] bg-zinc-950/95 backdrop-blur-xl flex flex-col p-6"
            >
              <div className="flex justify-between items-center mb-6">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-emerald-500/10 rounded-lg">
                    <Search className="w-5 h-5 text-emerald-500" />
                  </div>
                  <h2 className="text-xl font-bold text-zinc-100">{t.searchResorts}</h2>
                </div>
                <button 
                  onClick={() => setShowSearchPanel(false)}
                  className="p-2 hover:bg-zinc-800 rounded-full transition-colors"
                >
                  <X className="w-6 h-6 text-zinc-500" />
                </button>
              </div>

              <div className="relative mb-6">
                <input
                  type="text"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && searchResorts(searchQuery)}
                  placeholder={t.searchPlaceholder}
                  className="w-full bg-zinc-900 border border-zinc-800 rounded-2xl py-4 pl-12 pr-4 text-zinc-100 placeholder:text-zinc-600 focus:outline-none focus:border-emerald-500 transition-colors"
                />
                <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-zinc-600" />
                <button
                  onClick={() => searchResorts(searchQuery)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 p-2 bg-emerald-500 text-white rounded-xl hover:bg-emerald-400 transition-colors"
                >
                  <ArrowUpRight className="w-4 h-4" />
                </button>
              </div>

              <div className="flex-1 overflow-y-auto space-y-3 pr-2">
                {!currentPos && !searchQuery && (
                  <div className="p-4 bg-amber-500/10 border border-amber-500/20 rounded-2xl flex items-center gap-3 mb-2">
                    <MapPin className="w-5 h-5 text-amber-500 shrink-0" />
                    <p className="text-xs text-amber-200/80">{t.locationRequired}</p>
                  </div>
                )}
                
                <h3 className="text-xs font-bold text-zinc-500 uppercase tracking-widest mb-2">
                  {isSearchingResorts ? t.searchingResorts : t.nearbyResorts}
                </h3>
                
                {isSearchingResorts ? (
                  <div className="flex flex-col items-center justify-center py-12 gap-4">
                    <div className="w-8 h-8 border-4 border-emerald-500/20 border-t-emerald-500 rounded-full animate-spin" />
                    <span className="text-zinc-500 text-sm">{t.searchingResorts}</span>
                  </div>
                ) : !hasApiKey ? (
                  <div className="text-center py-12 text-zinc-400 bg-zinc-900/50 rounded-2xl border border-zinc-800 px-6">
                    <p className="font-bold mb-2 text-zinc-200">
                      {language === 'pl' ? "Wymagany Klucz API" : "API Key Required"}
                    </p>
                    <p className="text-sm opacity-80 mb-6">
                      {language === 'pl' 
                        ? "Aby korzystać z wyszukiwarki ośrodków, musisz wybrać klucz API Gemini." 
                        : "To use the resort search, you need to select a Gemini API key."}
                    </p>
                    <button 
                      onClick={handleSelectKey}
                      className="w-full py-3 bg-emerald-500 text-white rounded-xl font-bold hover:bg-emerald-400 transition-colors"
                    >
                      {language === 'pl' ? "Wybierz Klucz API" : "Select API Key"}
                    </button>
                    <a 
                      href="https://ai.google.dev/gemini-api/docs/billing" 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="block mt-4 text-xs text-zinc-500 underline"
                    >
                      {language === 'pl' ? "Dokumentacja bilingowa" : "Billing documentation"}
                    </a>
                  </div>
                ) : searchError ? (
                  <div className="text-center py-12 text-red-400 bg-red-500/5 rounded-2xl border border-red-500/20 px-4">
                    <p className="font-bold mb-1">Error</p>
                    <p className="text-sm opacity-80">{searchError}</p>
                    <button 
                      onClick={() => searchResorts(searchQuery)}
                      className="mt-4 px-4 py-2 bg-red-500 text-white rounded-xl text-sm font-bold"
                    >
                      Retry
                    </button>
                  </div>
                ) : resorts.length > 0 ? (
                  resorts.map((resort, idx) => (
                    <motion.a
                      key={idx}
                      href={resort.uri}
                      target="_blank"
                      rel="noopener noreferrer"
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: idx * 0.05 }}
                      className="flex items-center justify-between p-4 bg-zinc-900 border border-zinc-800 rounded-2xl hover:border-emerald-500/50 transition-all group"
                    >
                      <div className="flex items-center gap-3">
                        <div className="p-2 bg-zinc-800 rounded-lg group-hover:bg-emerald-500/10 transition-colors">
                          <MapPin className="w-5 h-5 text-zinc-400 group-hover:text-emerald-500" />
                        </div>
                        <span className="font-bold text-zinc-200 group-hover:text-white transition-colors">
                          {resort.title}
                        </span>
                      </div>
                      <ExternalLink className="w-4 h-4 text-zinc-600 group-hover:text-emerald-500 transition-colors" />
                    </motion.a>
                  ))
                ) : (
                  <div className="text-center py-12 text-zinc-600">
                    {t.noResortsFound}
                  </div>
                )}
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Settings Modal */}
        <AnimatePresence>
          {showSettings && (
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 z-[80] bg-zinc-950/95 backdrop-blur-xl flex flex-col items-center justify-center p-6"
            >
              <div className="w-full max-w-sm bg-zinc-900 border border-zinc-800 rounded-3xl p-6 shadow-2xl">
                <div className="flex justify-between items-center mb-8">
                  <div className="flex items-center gap-3">
                    <div className="p-2 bg-emerald-500/10 rounded-lg">
                      <SettingsIcon className="w-5 h-5 text-emerald-500" />
                    </div>
                    <h2 className="text-xl font-bold text-zinc-100">{t.settings}</h2>
                  </div>
                  <button 
                    onClick={() => setShowSettings(false)}
                    className="p-2 hover:bg-zinc-800 rounded-full transition-colors"
                  >
                    <X className="w-6 h-6 text-zinc-500" />
                  </button>
                </div>

                <div className="space-y-6">
                  <div>
                    <div className="flex items-center gap-2 text-zinc-400 mb-4">
                      <Globe className="w-4 h-4" />
                      <span className="text-sm font-bold uppercase tracking-wider">{t.selectLanguage}</span>
                    </div>
                    <div className="grid grid-cols-2 gap-3">
                      {(['en', 'de', 'es', 'pl'] as Language[]).map((lang) => (
                        <button
                          key={lang}
                          onClick={() => setLanguage(lang)}
                          className={`py-3 px-4 rounded-xl font-bold transition-all border ${
                            language === lang 
                              ? 'bg-emerald-500 border-emerald-400 text-white shadow-lg shadow-emerald-500/20' 
                              : 'bg-zinc-800 border-zinc-700 text-zinc-400 hover:border-zinc-500'
                          }`}
                        >
                          {lang === 'en' ? 'English' : lang === 'de' ? 'Deutsch' : lang === 'es' ? 'Español' : 'Polski'}
                        </button>
                      ))}
                    </div>
                  </div>

                  <div>
                    <div className="flex items-center gap-2 text-zinc-400 mb-4">
                      <Activity className="w-4 h-4" />
                      <span className="text-sm font-bold uppercase tracking-wider">{t.startTutorial}</span>
                    </div>
                    <button
                      onClick={() => {
                        setShowSettings(false);
                        setShowTutorial(true);
                        setTutorialStep(0);
                      }}
                      className="w-full py-4 bg-emerald-500 hover:bg-emerald-400 text-white rounded-xl font-bold transition-all shadow-lg shadow-emerald-500/20 flex items-center justify-center gap-2"
                    >
                      <Play className="w-5 h-5 fill-current" />
                      {t.startTutorial}
                    </button>
                  </div>
                </div>

                <button 
                  onClick={() => setShowSettings(false)}
                  className="w-full mt-10 py-4 bg-zinc-800 hover:bg-zinc-700 text-zinc-100 rounded-2xl font-bold transition-colors"
                >
                  {t.close}
                </button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>


      </main>

      {/* Footer / Status Bar */}
      <footer className="px-6 py-2 border-t border-zinc-800 bg-zinc-900 flex justify-between items-center text-[10px] text-zinc-500 font-mono uppercase tracking-widest">
        <div className="flex items-center gap-4">
          <span className="flex items-center gap-1">
            <div className={`w-1.5 h-1.5 rounded-full ${isTracking ? 'bg-emerald-500 animate-pulse' : 'bg-zinc-700'}`} />
            {t.gpsStatus}: {currentPos ? t.locked : t.searching}
          </span>
          <span>Lat: {currentPos?.[0]?.toFixed(4) || '---'}</span>
          <span>Lng: {currentPos?.[1]?.toFixed(4) || '---'}</span>
        </div>
        <div>v1.0.4-stable</div>
      </footer>

      {/* Tutorial Overlay */}
      <AnimatePresence>
        {showTutorial && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[100] pointer-events-none"
          >
            <motion.div 
              className="absolute inset-0 bg-black/40 backdrop-blur-[2px] pointer-events-auto" 
              onClick={() => setShowTutorial(false)}
              animate={{
                clipPath: highlightRect 
                  ? `polygon(0% 0%, 0% 100%, ${highlightRect.left - 4}px 100%, ${highlightRect.left - 4}px ${highlightRect.top - 4}px, ${highlightRect.left + highlightRect.width + 4}px ${highlightRect.top - 4}px, ${highlightRect.left + highlightRect.width + 4}px ${highlightRect.top + highlightRect.height + 4}px, ${highlightRect.left - 4}px ${highlightRect.top + highlightRect.height + 4}px, ${highlightRect.left - 4}px 100%, 100% 100%, 100% 0%)`
                  : 'polygon(0% 0%, 0% 100%, 100% 100%, 100% 0%)'
              }}
              transition={{ type: 'spring', damping: 25, stiffness: 200 }}
            />
            
            {/* Spotlight Highlight */}
            <AnimatePresence>
              {highlightRect && (
                <motion.div
                  initial={{ opacity: 0, scale: 0.8 }}
                  animate={{ 
                    opacity: 1, 
                    scale: 1,
                    top: highlightRect.top - 4,
                    left: highlightRect.left - 4,
                    width: highlightRect.width + 8,
                    height: highlightRect.height + 8,
                  }}
                  exit={{ opacity: 0, scale: 0.8 }}
                  className="absolute border-2 border-emerald-500 rounded-xl shadow-[0_0_30px_rgba(16,185,129,0.6)] z-[101] pointer-events-none bg-emerald-500/5"
                />
              )}
            </AnimatePresence>

            <motion.div
              key={tutorialStep}
              initial={{ scale: 0.9, opacity: 0, y: 10 }}
              animate={{ 
                scale: 1, 
                opacity: 1, 
                top: tooltipPos.top ?? 'auto',
                left: tooltipPos.left ?? 'auto',
                bottom: tooltipPos.bottom ?? 'auto',
                right: tooltipPos.right ?? 'auto',
                x: (tooltipPos.arrow === 'right' || tooltipPos.arrow === 'left') ? 0 : '-50%',
                y: (tooltipPos.arrow === 'top' || tooltipPos.arrow === 'bottom') ? 0 : '-50%',
                position: 'absolute'
              }}
              transition={{ type: 'spring', damping: 25, stiffness: 200 }}
              className="w-[280px] max-w-[calc(100vw-32px)] bg-zinc-900 border border-zinc-800 rounded-2xl p-5 shadow-2xl pointer-events-auto relative"
            >
              {/* Arrow */}
              {tooltipPos.arrow === 'top' && <div className="absolute -top-2 left-1/2 -translate-x-1/2 w-4 h-4 bg-zinc-900 border-t border-l border-zinc-800 rotate-45" />}
              {tooltipPos.arrow === 'bottom' && <div className="absolute -bottom-2 left-1/2 -translate-x-1/2 w-4 h-4 bg-zinc-900 border-b border-r border-zinc-800 rotate-45" />}
              {tooltipPos.arrow === 'right' && <div className="absolute top-1/2 -right-2 -translate-y-1/2 w-4 h-4 bg-zinc-900 border-t border-r border-zinc-800 rotate-45" />}

              <div className="flex justify-between items-start mb-3">
                <div>
                  <span className="text-[9px] font-mono text-emerald-500 uppercase tracking-widest mb-0.5 block">
                    {tutorialStep + 1} / {t.tutorialSteps.length}
                  </span>
                  <h2 className="text-lg font-bold text-zinc-100">{t.tutorialSteps[tutorialStep].title}</h2>
                </div>
                <button 
                  onClick={() => setShowTutorial(false)}
                  className="p-1 hover:bg-zinc-800 rounded-lg transition-colors"
                >
                  <X className="w-4 h-4 text-zinc-500" />
                </button>
              </div>
              
              <p className="text-zinc-400 text-sm leading-relaxed mb-6">
                {t.tutorialSteps[tutorialStep].content}
              </p>

              <div className="flex gap-2">
                <button
                  onClick={() => setShowTutorial(false)}
                  className="flex-1 py-2 text-zinc-500 text-xs font-bold hover:text-zinc-300 transition-colors"
                >
                  {t.skip}
                </button>
                <button
                  onClick={() => {
                    if (tutorialStep < t.tutorialSteps.length - 1) {
                      setTutorialStep(prev => prev + 1);
                    } else {
                      setShowTutorial(false);
                    }
                  }}
                  className="flex-[1.5] py-2.5 bg-emerald-500 hover:bg-emerald-400 text-white text-xs rounded-xl font-bold transition-all shadow-lg shadow-emerald-500/20"
                >
                  {tutorialStep < t.tutorialSteps.length - 1 ? t.next : t.finish}
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

function StatCard({ label, value, unit, icon }: { label: string, value: string, unit: string, icon: React.ReactNode }) {
  return (
    <div 
      className="bg-zinc-900/90 backdrop-blur-xl border border-zinc-800 p-1.5 rounded-xl shadow-lg flex flex-col justify-center min-w-0 transition-all"
    >
      <div className="flex items-center gap-1 text-zinc-500 mb-0.5 overflow-hidden">
        <span className="shrink-0">{icon}</span>
        <span className="text-[8px] font-bold uppercase tracking-tight truncate">{label}</span>
      </div>
      <div className="flex items-baseline gap-0.5 overflow-hidden">
        <span className="text-sm font-mono font-bold text-zinc-100 truncate">{value}</span>
        <span className="text-[8px] text-zinc-500 font-medium shrink-0">{unit}</span>
      </div>
    </div>
  );
}

function IconButton({ icon, onClick, active, id }: { icon: React.ReactNode, onClick?: () => void, active?: boolean, id?: string }) {
  return (
    <button 
      id={id}
      onClick={onClick}
      className={`p-3 backdrop-blur-xl border rounded-xl transition-all shadow-lg ${
        active 
          ? 'bg-emerald-500/20 border-emerald-500/50 text-emerald-500' 
          : 'bg-zinc-900/90 border-zinc-800 text-zinc-400 hover:text-emerald-500'
      }`}
    >
      {icon}
    </button>
  );
}
